// ══════════════════════════════════════════════════════
//  DATA: ALBUMS
// ══════════════════════════════════════════════════════
const ALBUMS=[
{id:"the-college-dropout",title:"The College Dropout",artist:"Kanye West",year:"2004",type:"official",tags:["kanye","west","college","dropout","rap","hip hop","2004"],cover:"https://i.scdn.co/image/ab67616d0000b27325b055377757b3cdd6f26b78",tracks:[
    {name:"Intro (Skit)",file:"../audio/kanye-west/the-college-dropout/tracks/intro.mp3",url:"https://open.spotify.com/track/7lIr3vVhpDkU5mQEDcnA0S",statId:"#CD_INTRO"},
    {name:"We Don't Care",file:"../audio/kanye-west/the-college-dropout/tracks/we-dont-care.mp3",url:"https://open.spotify.com/track/0IW0qaeyxL5Et4UG2MrJKB",statId:"#CD_WDC"},
    {name:"Graduation Day",file:"../audio/kanye-west/the-college-dropout/tracks/graduation-day.mp3",url:"https://open.spotify.com/track/7wL7Lb8Q3aYyq6gmRL0PZqQ",statId:"#CD_GRAD"},
    {name:"All Falls Down",file:"../audio/kanye-west/the-college-dropout/tracks/all-falls-down.mp3",url:"https://open.spotify.com/track/5SkRLpaGtvYPhw02vZhQQ9",statId:"#CD_AFD"},
    {name:"I'll Fly Away",file:"../audio/kanye-west/the-college-dropout/tracks/fly-away.mp3",url:"https://open.spotify.com/track/6MgGapP3EPFm9kYUvYBTZR",statId:"#CD_IFA"},
    {name:"Spaceship",file:"../audio/kanye-west/the-college-dropout/tracks/spaceship.mp3",url:"https://open.spotify.com/track/1ko2NuvWlQdxtNRc8QQzmT",statId:"#CD_SPACE"},
    {name:"Jesus Walks",file:"../audio/kanye-west/the-college-dropout/tracks/jesuswalks.mp3",url:"https://open.spotify.com/track/5g1vtHqi9uV7xtYeCcFOBx",statId:"#CD_JW"},
    {name:"Never Let Me Down",file:"../audio/kanye-west/the-college-dropout/tracks/never-let-me-down.mp3",url:"https://open.spotify.com/track/34j4OxJxKznBs88cjSL2j9",statId:"#CD_NLMD"},
    {name:"Get Em High",file:"../audio/kanye-west/the-college-dropout/tracks/get-em-high.mp3",url:"https://open.spotify.com/track/1PS1QMdUqOal0ai3Gt7sDQ",statId:"#CD_GEH"},
    {name:"Workout Plan (Skit)",file:"../audio/kanye-west/the-college-dropout/tracks/workout-plan.mp3",url:"https://open.spotify.com/track/2a1JSfTePKhysdIif2bzut",statId:"#CD_WPS"},
    {name:"The New Workout Plan",file:"../audio/kanye-west/the-college-dropout/tracks/new-workout-plan.mp3",url:"https://open.spotify.com/track/1Vp4St7JcXaUoJcIahtf3L",statId:"#CD_TNWP"},
    {name:"Slow Jamz",file:"../audio/kanye-west/the-college-dropout/tracks/slow-jamz.mp3",url:"https://open.spotify.com/track/3A4cpTBPaIQdtPFb5JxtaX",statId:"#CD_SJ"},
    {name:"Breathe In Breathe Out",file:"../audio/kanye-west/the-college-dropout/tracks/bibo.mp3",url:"https://open.spotify.com/track/4KFY4EEv9CN6ivrzD6vEvg",statId:"#CD_BIBO"},
    {name:"School Spirit (Skit 1)",file:"../audio/kanye-west/the-college-dropout/tracks/school-spirit-skit-1.mp3",url:"https://open.spotify.com/track/25mwJPzWVmS2yronBNQJF1",statId:"#CD_SSS1"},
    {name:"School Spirit",file:"../audio/kanye-west/the-college-dropout/tracks/school-spirit.mp3",url:"https://open.spotify.com/track/1th3G3okofWlvGWAAR7Y4V",statId:"#CD_SS"},
    {name:"School Spirit (Skit 2)",file:"../audio/kanye-west/the-college-dropout/tracks/school-spirit-skit-2.mp3",url:"https://open.spotify.com/track/5MAY7XyW322jMwLDtBQgsZ",statId:"#CD_SSS2"},
    {name:"Lil Jimmy (Skit)",file:"../audio/kanye-west/the-college-dropout/tracks/lil-jimmy-skit.mp3",url:"https://open.spotify.com/track/4BhwlQ9mTwhFGXpQvP9JTV"},
    {name:"Two Words",file:"../audio/kanye-west/the-college-dropout/tracks/2words.mp3",url:"https://open.spotify.com/track/62wtttQzoIA9HnNmGVd9Yq",statId:"#CD_2W"},
    {name:"Through the Wire",file:"../audio/kanye-west/the-college-dropout/tracks/through-the-wire.mp3",url:"https://open.spotify.com/track/4mmkhcEm1Ljy1U9nwtsxUo",statId:"#CD_TTW"},
    {name:"Family Business",file:"../audio/kanye-west/the-college-dropout/tracks/family-business.mp3",url:"https://open.spotify.com/track/5DBmXF7QO43Cuy9yqva116",statId:"#CD_FB"},
    {name:"Last Call",file:"../audio/kanye-west/the-college-dropout/tracks/lastcall.mp3",url:"https://open.spotify.com/track/7iOhWWYjhhQiXzF4o4HhXN",statId:"#CD_LC"}
]},
{id:"late-registration",title:"Late Registration",artist:"Kanye West",year:"2005",type:"official",tags:["kanye","west","late","registration","gold digger","diamonds","rap","hip hop","2005"],cover:"https://upload.wikimedia.org/wikipedia/en/thumb/f/f4/Late_registration_cd_cover.jpg/250px-Late_registration_cd_cover.jpg",tracks:[
    {name:"Wake Up Mr. West (Skit)",file:"../audio/kanye-west/late-registration/tracks/wake-up-mr_west.mp3"},{name:"Heard 'Em Say",file:"../audio/kanye-west/late-registration/tracks/heard-em-say.mp3",statId:"#LR_HES"},{name:"Touch the Sky",file:"../audio/kanye-west/late-registration/tracks/touch-the-sky.mp3",statId:"#LR_TTS"},
    {name:"Gold Digger",file:"../audio/kanye-west/late-registration/tracks/gold-digger.mp3",statId:"#LR_GD"},{name:"Drive Slow",file:"../audio/kanye-west/late-registration/tracks/drive-slow.mp3",statId:"#LR_DS"},{name:"My Way Home (Skit)",file:"../audio/kanye-west/late-registration/tracks/my-way-home-skit.mp3"},
    {name:"Crack Music",file:"../audio/kanye-west/late-registration/tracks/crack-music.mp3",statId:"#LR_CM"},{name:"Roses",file:"../audio/kanye-west/late-registration/tracks/roses.mp3",statId:"#LR_ROSES"},{name:"Bring Me Down",file:"../audio/kanye-west/late-registration/tracks/bring-me-down.mp3",statId:"#LR_BMD"},
    {name:"Addiction",file:"../audio/kanye-west/late-registration/tracks/addiction.mp3",statId:"#LR_ADD"},{name:"Diamonds from Sierra Leone (Remix)",file:"../audio/kanye-west/late-registration/tracks/diamonds.mp3",statId:"#LR_DIAM"},
    {name:"We Major",file:"../audio/kanye-west/late-registration/tracks/we-major.mp3",statId:"#LR_WM"},{name:"Hey Mama",file:"../audio/kanye-west/late-registration/tracks/hey-mama.mp3",statId:"#LR_HM"},{name:"Celebration",file:"../audio/kanye-west/late-registration/tracks/celebration.mp3",statId:"#LR_CEL"},
    {name:"Gone",file:"../audio/kanye-west/late-registration/tracks/gone.mp3",statId:"#LR_GONE"},{name:"Late",file:"../audio/kanye-west/late-registration/tracks/late.mp3",statId:"#LR_LATE"},{name:"Number One",file:"../audio/kanye-west/late-registration/tracks/number-one.mp3",statId:"#LR_N1"},{name:"We Can Make It Better",file:"../audio/kanye-west/late-registration/tracks/we-can-make-it.mp3",statId:"#LR_WCMIB"}
]},
{id:"graduation",title:"Graduation",artist:"Kanye West",year:"2007",type:"official",tags:["kanye","west","graduation","stronger","good morning","rap","hip hop","2007"],cover:"https://m.media-amazon.com/images/I/71pxGj4RoVS._AC_UF894,1000_QL80_.jpg",tracks:[
    {name:"Good Morning",file:"../audio/kanye-west/graduation/tracks/good-morning.mp3",statId:"#GR_GM"},{name:"Champion",file:"../audio/kanye-west/graduation/tracks/champion.mp3",statId:"#GR_CHAMP"},{name:"Stronger",file:"../audio/kanye-west/graduation/tracks/stronger.mp3",statId:"#GR_STR"},
    {name:"I Wonder",file:"../audio/kanye-west/graduation/tracks/i-wonder.mp3",statId:"#GR_IW"},{name:"Good Life",file:"../audio/kanye-west/graduation/tracks/good-life.mp3",statId:"#GR_GL"},{name:"Can't Tell Me Nothing",file:"../audio/kanye-west/graduation/tracks/cant-tell-me-nothing.mp3",statId:"#GR_CTMN"},
    {name:"Barry Bonds",file:"../audio/kanye-west/graduation/tracks/barry-bonds.mp3",statId:"#GR_BB"},{name:"Drunk and Hot Girls",file:"../audio/kanye-west/graduation/tracks/drunk-hot-girls.mp3",statId:"#GR_DHG"},{name:"Flashing Lights",file:"../audio/kanye-west/graduation/tracks/flashing-lights.mp3",statId:"#GR_FL"},
    {name:"Everything I Am",file:"../audio/kanye-west/graduation/tracks/everything-i-am.mp3",statId:"#GR_EIA"},{name:"The Glory",file:"../audio/kanye-west/graduation/tracks/the-glory.mp3",statId:"#GR_TG"},{name:"Homecoming",file:"../audio/kanye-west/graduation/tracks/homecoming.mp3",statId:"#GR_HC"},{name:"Big Brother",file:"../audio/kanye-west/graduation/tracks/big-brother.mp3",statId:"#GR_BIG"}
]},
{id:"808s",title:"808s & Heartbreak",artist:"Kanye West",year:"2008",type:"official",tags:["kanye","west","808s","heartbreak","heartless","love lockdown","autotune","rap","pop","2008"],cover:"https://m.media-amazon.com/images/I/51-HCBAsFRL._UF1000,1000_QL80_.jpg",tracks:[
    {name:"Say You Will",file:"../audio/kanye-west/808s-n-heartbreak/tracks/say-you-will.mp3",statId:"#808_SYW"},{name:"Welcome to Heartbreak",file:"../audio/kanye-west/808s-n-heartbreak/tracks/welcome-to-heartbreak.mp3",statId:"#808_WTH"},{name:"Heartless",file:"../audio/kanye-west/808s-n-heartbreak/tracks/heartless.mp3",statId:"#808_HL"},
    {name:"Amazing",file:"../audio/kanye-west/808s-n-heartbreak/tracks/amazing.mp3",statId:"#808_AMAZ"},{name:"Love Lockdown",file:"../audio/kanye-west/808s-n-heartbreak/tracks/love-lockdown.mp3",statId:"#808_LL"},{name:"Paranoid",file:"../audio/kanye-west/808s-n-heartbreak/tracks/paranoid.mp3",statId:"#808_PAR"},
    {name:"RoboCop",file:"../audio/kanye-west/808s-n-heartbreak/tracks/robocop.mp3",statId:"#808_RC"},{name:"Street Lights",file:"../audio/kanye-west/808s-n-heartbreak/tracks/street-lights.mp3",statId:"#808_SL"},{name:"Bad News",file:"../audio/kanye-west/808s-n-heartbreak/tracks/bad-news.mp3",statId:"#808_BN"},
    {name:"See You in My Nightmares",file:"../audio/kanye-west/808s-n-heartbreak/tracks/see-you-in-my-nightmares.mp3",statId:"#808_SYMN"},{name:"Coldest Winter",file:"../audio/kanye-west/808s-n-heartbreak/tracks/coldest-winter.mp3",statId:"#808_CW"},{name:"Pinocchio Story (Live)",file:"../audio/kanye-west/808s-n-heartbreak/tracks/pinocchio-story.mp3",statId:"#808_PS"}
]},
{id:"mbdtf",title:"My Beautiful Dark Twisted Fantasy",artist:"Kanye West",year:"2010",type:"official",tags:["kanye","west","mbdtf","beautiful","dark","twisted","fantasy","runaway","power","rap","hip hop","2010"],cover:"https://i.scdn.co/image/ab67616d0000b273d9194aa18fa4c9362b47464f",tracks:[
    {name:"Dark Fantasy",file:"../audio/kanye-west/mbdtf/tracks/dark-fantasy.mp3",statId:"#MBDTF_DF"},{name:"Gorgeous",file:"../audio/kanye-west/mbdtf/tracks/gorgeous.mp3",statId:"#MBDTF_GOR"},{name:"POWER",file:"../audio/kanye-west/mbdtf/tracks/power.mp3",statId:"#MBDTF_PWR"},
    {name:"All of the Lights (Interlude)",file:"../audio/kanye-west/mbdtf/tracks/all-of-lights-interlude.mp3",statId:"#MBDTF_AOLI"},{name:"All of the Lights",file:"../audio/kanye-west/mbdtf/tracks/all-of-lights.mp3",statId:"#MBDTF_AOL"},
    {name:"Monster",file:"../audio/kanye-west/mbdtf/tracks/monster.mp3",statId:"#MBDTF_MON"},{name:"So Appalled",file:"../audio/kanye-west/mbdtf/tracks/so-appalled.mp3",statId:"#MBDTF_SA"},{name:"Devil in a New Dress",file:"../audio/kanye-west/mbdtf/tracks/devil-new-dress.mp3",statId:"#MBDTF_DIAND"},
    {name:"Runaway",file:"../audio/kanye-west/mbdtf/tracks/runaway.mp3",statId:"#MBDTF_RUN"},{name:"Hell of a Life",file:"../audio/kanye-west/mbdtf/tracks/hell-of-a-life.mp3",statId:"#MBDTF_HOAL"},{name:"Blame Game",file:"../audio/kanye-west/mbdtf/tracks/blame-game.mp3",statId:"#MBDTF_BG"},
    {name:"Lost in the World",file:"../audio/kanye-west/mbdtf/tracks/lost-in-the-world.mp3",statId:"#MBDTF_LITW"},{name:"Who Will Survive in America",file:"../audio/kanye-west/mbdtf/tracks/who-will-survive.mp3",statId:"#MBDTF_WWSIA"}
]},
{id:"watch-throne",title:"Watch the Throne",artist:"JAŸ-Z",primaryArtist:"Kanye West",featuredArtists:["Jay-Z"],year:"2011",type:"official",tags:["kanye","west","jayz","watch","throne","niggas in paris","rap","hip hop","2011"],cover:"https://upload.wikimedia.org/wikipedia/en/thumb/e/ee/Watch_The_Throne.jpg/250px-Watch_The_Throne.jpg",tracks:[
    {name:"No Church in the Wild",file:"../audio/kanye-west/watch-the-thrown/tracks/no-church.mp3",statId:"#WTT_NCITW"},{name:"Lift Off",file:"../audio/kanye-west/watch-the-thrown/tracks/lift-off.mp3",statId:"#WTT_LO"},{name:"Niggas in Paris",file:"../audio/kanye-west/watch-the-thrown/tracks/niggas-in-paris.mp3",statId:"#WTT_NIP"},
    {name:"Otis",file:"../audio/kanye-west/watch-the-thrown/tracks/otis.mp3",statId:"#WTT_OTIS"},{name:"Gotta Have It",file:"../audio/kanye-west/watch-the-thrown/tracks/gotta-have-it.mp3",statId:"#WTT_GHI"},{name:"New Day",file:"../audio/kanye-west/watch-the-thrown/tracks/new-day.mp3",statId:"#WTT_ND"},
    {name:"That's My Bitch",file:"../audio/kanye-west/watch-the-thrown/tracks/thats-my-bitch.mp3",statId:"#WTT_TMB"},{name:"Welcome to the Jungle",file:"../audio/kanye-west/watch-the-thrown/tracks/welcome-jungle.mp3",statId:"#WTT_WTTJ"},{name:"Who Gon Stop Me",file:"../audio/kanye-west/watch-the-thrown/tracks/who-gon-stop-me.mp3",statId:"#WTT_WGSM"},
    {name:"Murder to Excellence",file:"../audio/kanye-west/watch-the-thrown/tracks/murder-excellence.mp3",statId:"#WTT_MTE"},{name:"Sweet Baby Jesus",file:"../audio/kanye-west/watch-the-thrown/tracks/sweet-baby-jesus.mp3"},{name:"Why I Love You",file:"../audio/kanye-west/watch-the-thrown/tracks/why-i-love-you.mp3",statId:"#WTT_WILY"},
    {name:"H•A•M",file:"../audio/kanye-west/watch-the-thrown/tracks/ham.mp3",statId:"#WTT_HAM"},{name:"Primetime",file:"../audio/kanye-west/watch-the-thrown/tracks/primetime.mp3",statId:"#WTT_PT"},{name:"The Joy",file:"../audio/kanye-west/watch-the-thrown/tracks/the-joy.mp3",statId:"#WTT_TJ"}
]},
{id:"cruel-summer",title:"Cruel Summer",artist:"GOOD Music",primaryArtist:"Kanye West",featuredArtists:["Big Sean","2 Chainz","John Legend","Teyana Taylor"],year:"2012",type:"official",tags:["kanye","west","good","music","cruel","summer","mercy","clique","rap","hip hop","2012"],cover:"https://upload.wikimedia.org/wikipedia/en/thumb/a/ab/CruelSummercover.jpg/250px-CruelSummercover.jpg",tracks:[
    {name:"To the World",file:"../audio/kanye-west/cruel-summer/tracks/to-the-world.mp3",statId:"#CS_TTW"},{name:"Mercy",file:"../audio/kanye-west/cruel-summer/tracks/mercy.mp3",statId:"#CS_MERCY"},{name:"New God Flow",file:"../audio/kanye-west/cruel-summer/tracks/new-god-flow.mp3",statId:"#CS_NGF"},
    {name:"Clique",file:"../audio/kanye-west/cruel-summer/tracks/clique.mp3",statId:"#CS_CLIQUE"},{name:"Bliss",file:"../audio/kanye-west/cruel-summer/tracks/bliss.mp3",statId:"#CS_BLISS"},{name:"Cruel Summer",file:"../audio/kanye-west/cruel-summer/tracks/cruel-summer.mp3",statId:"#CS_CS"},
    {name:"Higher",file:"../audio/kanye-west/cruel-summer/tracks/higher.mp3",statId:"#CS_HIGH"},{name:"Don't Like (Remix)",file:"../audio/kanye-west/cruel-summer/tracks/dont-like.mp3",statId:"#CS_DL"},{name:"The Morning",file:"../audio/kanye-west/cruel-summer/tracks/the-morning.mp3",statId:"#CS_TM"},
    {name:"Cold",file:"../audio/kanye-west/cruel-summer/tracks/cold.mp3",statId:"#CS_COLD"},{name:"Sweet Baby Jesus",file:"../audio/kanye-west/cruel-summer/tracks/sweet-baby-jesus.mp3",statId:"#CS_SBJ"},{name:"Sin City",file:"../audio/kanye-west/cruel-summer/tracks/sin-city.mp3",statId:"#CS_SC"},
    {name:"Way Too Cold",file:"../audio/kanye-west/cruel-summer/tracks/way-too-cold.mp3",statId:"#CS_WTC"},{name:"Creepers",file:"../audio/kanye-west/cruel-summer/tracks/creepers.mp3",statId:"#CS_CREEP"}
]},
{id:"yeezus",title:"Yeezus",artist:"Kanye West",year:"2013",type:"official",tags:["kanye","west","yeezus","bound 2","new slaves","black skinhead","rap","industrial","2013"],cover:"https://m.media-amazon.com/images/I/516qybuOZhL._UF1000,1000_QL80_.jpg",tracks:[
    {name:"On Sight",file:"../audio/kanye-west/YEEZUS/tracks/on-sight.mp3",statId:"#YZ_OS"},{name:"Black Skinhead",file:"../audio/kanye-west/YEEZUS/tracks/black-skinhead.mp3",statId:"#YZ_BSH"},{name:"I Am a God",file:"../audio/kanye-west/YEEZUS/tracks/i-am-a-god.mp3",statId:"#YZ_IAAG"},
    {name:"New Slaves",file:"../audio/kanye-west/YEEZUS/tracks/new-slaves.mp3",statId:"#YZ_NS"},{name:"Hold My Liquor",file:"../audio/kanye-west/YEEZUS/tracks/hold-my-liquor.mp3",statId:"#YZ_HML"},{name:"I'm in It",file:"../audio/kanye-west/YEEZUS/tracks/im-in-it.mp3",statId:"#YZ_III"},
    {name:"Blood on the Leaves",file:"../audio/kanye-west/YEEZUS/tracks/blood-on-leaves.mp3",statId:"#YZ_BOTL"},{name:"Guilt Trip",file:"../audio/kanye-west/YEEZUS/tracks/guilt-trip.mp3",statId:"#YZ_GT"},{name:"Send It Up",file:"../audio/kanye-west/YEEZUS/tracks/send-it-up.mp3",statId:"#YZ_SIU"},
    {name:"Bound 2",file:"../audio/kanye-west/YEEZUS/tracks/bound-2.mp3",statId:"#YZ_B2"}
]},
{id:"tlop",title:"The Life of Pablo",artist:"Kanye West",year:"2016",type:"official",tags:["kanye","west","pablo","tlop","ultralight beam","famous","fade","rap","gospel","2016"],cover:"https://preview.redd.it/puu7vsw10fb01.png?width=640&crop=smart&auto=webp&s=cef42bec02f7a6064349d8cfd34df097bfe12ade",tracks:[
    {name:"Ultralight Beam",file:"../audio/kanye-west/the-life-of-pablo/tracks/ultralight-beam.mp3",statId:"#TLOP_UB"},{name:"Father Stretch My Hands Pt. 1",file:"../audio/kanye-west/the-life-of-pablo/tracks/fsmh-pt1.mp3",statId:"#TLOP_FSMH1"},
    {name:"Pt. 2",file:"../audio/kanye-west/the-life-of-pablo/tracks/fsmh-pt2.mp3",statId:"#TLOP_FSMH2"},{name:"Famous",file:"../audio/kanye-west/the-life-of-pablo/tracks/famous.mp3",statId:"#TLOP_FAM"},{name:"Feedback",file:"../audio/kanye-west/the-life-of-pablo/tracks/feedback.mp3",statId:"#TLOP_FB"},
    {name:"Low Lights",file:"../audio/kanye-west/the-life-of-pablo/tracks/low-lights.mp3",statId:"#TLOP_LL"},{name:"Highlights",file:"../audio/kanye-west/the-life-of-pablo/tracks/highlights.mp3",statId:"#TLOP_HL"},{name:"Freestyle 4",file:"../audio/kanye-west/the-life-of-pablo/tracks/freestyle-4.mp3",statId:"#TLOP_F4"},
    {name:"I Love Kanye",file:"../audio/kanye-west/the-life-of-pablo/tracks/i-love-kanye.mp3",statId:"#TLOP_ILK"},{name:"Waves",file:"../audio/kanye-west/the-life-of-pablo/tracks/waves.mp3",statId:"#TLOP_WAV"},{name:"FML",file:"../audio/kanye-west/the-life-of-pablo/tracks/fml.mp3",statId:"#TLOP_FML"},
    {name:"Real Friends",file:"../audio/kanye-west/the-life-of-pablo/tracks/real-friends.mp3",statId:"#TLOP_RF"},{name:"Wolves",file:"../audio/kanye-west/the-life-of-pablo/tracks/wolves.mp3",statId:"#TLOP_WLV"},{name:"Frank's Track",file:"../audio/kanye-west/the-life-of-pablo/tracks/franks-track,mp3"},
    {name:"Siiiiiiiiilver Surfffter Surffffff",file:"../audio/kanye-west/the-life-of-pablo/tracks/silver-surfer.mp3",statId:"#TLOP_SS"},{name:"30 Hours",file:"../audio/kanye-west/the-life-of-pablo/tracks/30-hours.mp3",statId:"#TLOP_30H"},
    {name:"No More Parties in LA",file:"../audio/kanye-west/the-life-of-pablo/tracks/no-more-parties.mp3",statId:"#TLOP_NMPLA"},{name:"Facts (Charlie Heat Version)",file:"../audio/kanye-west/the-life-of-pablo/tracks/facts.mp3",statId:"#TLOP_FACTS"},
    {name:"Fade",file:"../audio/kanye-west/the-life-of-pablo/tracks/fade.mp3",statId:"#TLOP_FADE"},{name:"Saint Pablo",file:"../audio/kanye-west/the-life-of-pablo/tracks/saint-pablo.mp3",statId:"#TLOP_SP"}
]},
{id:"ye",title:"ye",artist:"Kanye West",year:"2018",type:"official",tags:["kanye","west","ye","yikes","ghost town","violent crimes","rap","2018"],cover:"https://upload.wikimedia.org/wikipedia/en/7/74/Ye_album_cover.jpg",tracks:[
    {name:"I Thought About Killing You",file:"../audio/kanye-west/ye/tracks/i-thought-about.mp3",statId:"#YE_ITAKY"},{name:"Yikes",file:"../audio/kanye-west/ye/tracks/yikes.mp3",statId:"#YE_YK"},{name:"All Mine",file:"../audio/kanye-west/ye/tracks/all-mine.mp3",statId:"#YE_AM"},
    {name:"Wouldn't Leave",file:"../audio/kanye-west/ye/tracks/wouldnt-leave.mp3",statId:"#YE_WL"},{name:"No Mistakes",file:"../audio/kanye-west/ye/tracks/no-mistakes.mp3",statId:"#YE_NM"},{name:"Ghost Town",file:"../audio/kanye-west/ye/tracks/ghost-town.mp3",statId:"#YE_GT"},
    {name:"Violent Crimes",file:"../audio/kanye-west/ye/tracks/violent-crimes.mp3",statId:"#YE_VC"}
]},
{id:"kids-see-ghosts",title:"Kids See Ghosts",artist:"Kids See Ghosts",primaryArtist:"Kanye West",featuredArtists:["Kid Cudi"],year:"2018",type:"official",tags:["kanye","west","cudi","kids","see","ghosts","reborn","rap","2018"],cover:"https://upload.wikimedia.org/wikipedia/en/4/44/Kids_See_Ghosts_Cover.png",tracks:[
    {name:"Feel the Love",file:"../audio/kanye-west/kids-see-ghosts/tracks/feel-the-love.mp3",statId:"#KSG_FTL"},
    {name:"Fire",file:"../audio/kanye-west/kids-see-ghosts/tracks/fire.mp3",statId:"#KSG_FIRE"},
    {name:"4th Dimension",file:"../audio/kanye-west/kids-see-ghosts/tracks/4th-dimension.mp3",statId:"#KSG_4D"},
    {name:"Freeee (Ghost Town Pt. 2)",file:"../audio/kanye-west/kids-see-ghosts/tracks/freeee.mp3",statId:"#KSG_FREE"},
    {name:"Reborn",file:"../audio/kanye-west/kids-see-ghosts/tracks/reborn.mp3",statId:"#KSG_REB"},
    {name:"Kids See Ghosts",file:"../audio/kanye-west/kids-see-ghosts/tracks/kids-see-ghosts.mp3",statId:"#KSG_KSG"},
    {name:"Cudi Montage",file:"../audio/kanye-west/kids-see-ghosts/tracks/cudi-montage.mp3",statId:"#KSG_CM"}
]},
{id:"jesus-is-king",title:"Jesus Is King",artist:"Kanye West",year:"2019",type:"official",tags:["kanye","west","jesus","king","gospel","follow god","closed on sunday","rap","2019"],cover:"https://media.pitchfork.com/photos/5db73da8fd8a1f0009ad5c80/master/pass/jesusisking_kanye.jpg",tracks:[
    {name:"Every Hour",file:"../audio/kanye-west/jesus-is-king/tracks/every-hour.mp3",statId:"#JIK_EH"},
    {name:"Follow God",file:"../audio/kanye-west/jesus-is-king/tracks/follow-god.mp3",statId:"#JIK_FG"},
    {name:"Closed on Sunday",file:"../audio/kanye-west/jesus-is-king/tracks/closed-on-sunday.mp3",statId:"#JIK_COS"},
    {name:"On God",file:"../audio/kanye-west/jesus-is-king/tracks/on-god.mp3",statId:"#JIK_OG"},
    {name:"Everything We Need",file:"../audio/kanye-west/jesus-is-king/tracks/everything-we-need.mp3",statId:"#JIK_EWN"},
    {name:"Water",file:"../audio/kanye-west/jesus-is-king/tracks/water.mp3",statId:"#JIK_WAT"},
    {name:"God Is",file:"../audio/kanye-west/jesus-is-king/tracks/god-is.mp3",statId:"#JIK_GI"},
    {name:"Hands On",file:"../audio/kanye-west/jesus-is-king/tracks/hands-on.mp3",statId:"#JIK_HO"},
    {name:"Use This Gospel",file:"../audio/kanye-west/jesus-is-king/tracks/use-this-gospel.mp3",statId:"#JIK_UTG"},
    {name:"Jesus Is Lord",file:"../audio/kanye-west/jesus-is-king/tracks/jesus-is-lord.mp3",statId:"#JIK_JIL"}
]},
{id:"donda",title:"Donda",artist:"Kanye West",year:"2021",type:"official",tags:["kanye","west","donda","off the grid","hurricane","praise god","jail","rap","gospel","2021"],cover:"https://i.redd.it/jvst2ity53d51.jpg",tracks:[
    {name:"Donda Chant",file:"../audio/kanye-west/donda/tracks/donda-chant.mp3",statId:"#DON_DC"},{name:"Jail",file:"../audio/kanye-west/donda/tracks/jail.mp3",statId:"#DON_JAIL"},{name:"God Breathed",file:"../audio/kanye-west/donda/tracks/god-breathed.mp3",statId:"#DON_GB"},
    {name:"Off the Grid",file:"../audio/kanye-west/donda/tracks/off-the-grid.mp3",statId:"#DON_OTG"},{name:"Hurricane",file:"../audio/kanye-west/donda/tracks/hurricane.mp3",statId:"#DON_HUR"},{name:"Praise God",file:"../audio/kanye-west/donda/tracks/praise-god.mp3",statId:"#DON_PG"},
    {name:"Jonah",file:"../audio/kanye-west/donda/tracks/jonah.mp3",statId:"#DON_JON"},{name:"Ok Ok",file:"../audio/kanye-west/donda/tracks/ok-ok.mp3",statId:"#DON_OO"},{name:"Junya",file:"../audio/kanye-west/donda/tracks/junya.mp3",statId:"#DON_JUN"},
    {name:"Believe What I Say",file:"../audio/kanye-west/donda/tracks/believe-what-i-say.mp3",statId:"#DON_BWIS"},{name:"24",file:"../audio/kanye-west/donda/tracks/24.mp3",statId:"#DON_24"},{name:"Remote Control",file:"../audio/kanye-west/donda/tracks/remote-control.mp3",statId:"#DON_RC"},
    {name:"Moon",file:"../audio/kanye-west/donda/tracks/moon.mp3",statId:"#DON_MOON"},{name:"Heaven and Hell",file:"../audio/kanye-west/donda/tracks/heaven-and-hell.mp3",statId:"#DON_HAH"},{name:"Donda",file:"../audio/kanye-west/donda/tracks/donda-title.mp3",statId:"#DON_DON"},
    {name:"Pure Souls",file:"../audio/kanye-west/donda/tracks/pure-souls.mp3",statId:"#DON_PS"},{name:"Come to Life",file:"../audio/kanye-west/donda/tracks/come-to-life.mp3",statId:"#DON_CTL"},{name:"No Child Left Behind",file:"../audio/kanye-west/donda/tracks/no-child.mp3",statId:"#DON_NCLB"},
    {name:"Jail pt 2",file:"../audio/kanye-west/donda/tracks/jail-pt2.mp3",statId:"#DON_JAIL2"},{name:"Jesus Lord",file:"../audio/kanye-west/donda/tracks/jesus-lord.mp3",statId:"#DON_JL"},{name:"New Again",file:"../audio/kanye-west/donda/tracks/new-again.mp3",statId:"#DON_NA"},
    {name:"Tell the Vision",file:"../audio/kanye-west/donda/tracks/tell-the-vision.mp3",statId:"#DON_TTV"},{name:"Lord I Need You",file:"../audio/kanye-west/donda/tracks/lord-i-need-you.mp3",statId:"#DON_LINY"},{name:"Jail pt 3",file:"../audio/kanye-west/donda/tracks/jail-pt3.mp3"}
]},
{id:"donda-2",title:"Donda 2",artist:"Kanye West",year:"2022",type:"official",tags:["kanye","west","donda","2","stem player","rap","2022"],cover:"https://i.scdn.co/image/ab67616d0000b2736dc675e2b4f4d86b762f3bfa",tracks:[
    {name:"Sci Fi",file:"../audio/kanye-west/donda-2/tracks/sci-fi.mp3",statId:"#D2_SF"},{name:"True Love",file:"../audio/kanye-west/donda-2/tracks/true-love.mp3",statId:"#D2_TL"},{name:"Security",file:"../audio/kanye-west/donda-2/tracks/security.mp3",statId:"#D2_SEC"},
    {name:"Too Easy",file:"../audio/kanye-west/donda-2/tracks/too-easy.mp3",statId:"#D2_TE"},{name:"Louie Bags",file:"../audio/kanye-west/donda-2/tracks/louie-bags.mp3",statId:"#D2_LB"},{name:"Pablo",file:"../audio/kanye-west/donda-2/tracks/pablo.mp3",statId:"#D2_PAB"},
    {name:"Rich Flex",file:"../audio/kanye-west/donda-2/tracks/rich-flex.mp3",statId:"#D2_RF"},{name:"Happy",file:"../audio/kanye-west/donda-2/tracks/happy.mp3",statId:"#D2_HAP"},
    {name:"We Did It Kid",file:"../audio/kanye-west/donda-2/tracks/we-did-it-kid.mp3",statId:"#D2_WDIK"},{name:"Flowers",file:"../audio/kanye-west/donda-2/tracks/flowers.mp3",statId:"#D2_FLW"}
]},
{id:"vultures-1",title:"Vultures 1",artist:"¥$",primaryArtist:"Kanye West",featuredArtists:["Ty Dolla $ign"],year:"2024",type:"official",tags:["kanye","west","ty dolla sign","vultures","carnival","hoodrat","rap","2024"],cover:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Kanye_West_and_Ty_Dolla_Sign_-_Vultures_Vol._1_%28Cover%29.png/250px-Kanye_West_and_Ty_Dolla_Sign_-_Vultures_Vol._1_%28Cover%29.png",tracks:[
    {name:"Vultures",file:"../audio/kanye-west/vultures-1/tracks/vultures-title.mp3",statId:"#V1_VUL"},{name:"Paid",file:"../audio/kanye-west/vultures-1/tracks/paid.mp3",statId:"#V1_PAID"},
    {name:"Hoodrat",file:"../audio/kanye-west/vultures-1/tracks/hoodrat.mp3",statId:"#V1_HR"},{name:"Talking",file:"../audio/kanye-west/vultures-1/tracks/talking.mp3",statId:"#V1_TALK"},
    {name:"Carnival",file:"../audio/kanye-west/vultures-1/tracks/carnival.mp3",statId:"#V1_CARN"},{name:"Burn",file:"../audio/kanye-west/vultures-1/tracks/burn.mp3",statId:"#V1_BURN"},
    {name:"King",file:"../audio/kanye-west/vultures-1/tracks/king.mp3",statId:"#V1_KING"},{name:"Keys to My Life",file:"../audio/kanye-west/vultures-1/tracks/keys-to-my-life.mp3",statId:"#V1_KTML"},
    {name:"FML (feat. The Weeknd)",file:"../audio/kanye-west/vultures-1/tracks/fml.mp3"},
    {name:"Problematic",file:"../audio/kanye-west/vultures-1/tracks/problematic.mp3",statId:"#V1_PROB"},{name:"Good (Don't Die)",file:"../audio/kanye-west/vultures-1/tracks/good-dont-die.mp3",statId:"#V1_GDD"},
    {name:"Do It",file:"../audio/kanye-west/vultures-1/tracks/do-it.mp3",statId:"#V1_DI"},{name:"Beg Forgiveness",file:"../audio/kanye-west/vultures-1/tracks/beg-forgiveness.mp3",statId:"#V1_BF"},
    {name:"Paperwork",file:"../audio/kanye-west/vultures-1/tracks/paperwork.mp3",statId:"#V1_PW"},{name:"Back to Me",file:"../audio/kanye-west/vultures-1/tracks/back-to-me.mp3",statId:"#V1_BTM"},
    {name:"Vultures 2",file:"../audio/kanye-west/vultures-1/tracks/vultures-2-track.mp3",statId:"#V1_V2"},{name:"Lifestyle",file:"../audio/kanye-west/vultures-1/tracks/lifestyle.mp3",statId:"#V1_LS"}
]},
{id:"vultures-2",title:"Vultures 2",artist:"¥$",primaryArtist:"Kanye West",featuredArtists:["Ty Dolla $ign"],year:"2024",type:"official",tags:["kanye","west","ty dolla sign","vultures","2","rap","2024"],cover:"https://images.genius.com/8e2c3c0e076e066fa40966001b956663.1000x1000x1.jpg",tracks:[
    {name:"Field Trip",file:"../audio/kanye-west/vultures-2/tracks/field-trip.mp3",statId:"#V2_FT"},{name:"Everybody",file:"../audio/kanye-west/vultures-2/tracks/everybody.mp3",statId:"#V2_EVB"},
    {name:"Bomb",file:"../audio/kanye-west/vultures-2/tracks/bomb.mp3",statId:"#V2_BOMB"},{name:"River",file:"../audio/kanye-west/vultures-2/tracks/river.mp3",statId:"#V2_RIV"},
    {name:"Science",file:"../audio/kanye-west/vultures-2/tracks/science.mp3",statId:"#V2_SCI"},{name:"Munch",file:"../audio/kanye-west/vultures-2/tracks/munch.mp3",statId:"#V2_MUNCH"},
    {name:"Drive",file:"../audio/kanye-west/vultures-2/tracks/drive.mp3",statId:"#V2_DRV"},{name:"Mast",file:"../audio/kanye-west/vultures-2/tracks/mast.mp3",statId:"#V2_MAST"},
    {name:"Beg",file:"../audio/kanye-west/vultures-2/tracks/beg.mp3",statId:"#V2_BEG"},{name:"Lonely Roads",file:"../audio/kanye-west/vultures-2/tracks/lonely-roads.mp3",statId:"#V2_LR"},
    {name:"Gun To My Head",file:"../audio/kanye-west/vultures-2/tracks/gun-to-my-head.mp3",statId:"#V2_GTMH"},
    {name:"Preacher Man",file:"../audio/kanye-west/vultures-2/tracks/preacher-man.mp3",statId:"#V2_PM"},
    {name:"Slide",file:"../audio/kanye-west/vultures-2/tracks/slide.mp3",statId:"#V2_SLD"},
    {name:"Fvcking Demons",file:"../audio/kanye-west/vultures-2/tracks/fvcking-demons.mp3",statId:"#V2_FD"}
]},
{id:"bully",title:"Bully",artist:"Kanye West",year:"2025",type:"official",tags:["kanye","west","ye","bully","rap","2025"],cover:"https://news.artnet.com/app/news-upload/2024/10/kanye-west-bully-ye.jpg",tracks:[
    {name:"Bully",file:"../audio/kanye-west/bully/tracks/bully-title.mp3",statId:"#BUL_BUL"},{name:"Lonely",file:"../audio/kanye-west/bully/tracks/lonely.mp3",statId:"#BUL_LON"},
    {name:"Industry",file:"../audio/kanye-west/bully/tracks/industry.mp3",statId:"#BUL_IND"},{name:"Witches",file:"../audio/kanye-west/bully/tracks/witches.mp3",statId:"#BUL_WIT"},
    {name:"Field Trip",file:"../audio/kanye-west/bully/tracks/field-trip.mp3"},
    {name:"New Body",file:"../audio/kanye-west/bully/tracks/new-body.mp3",statId:"#BUL_NB"},
    {name:"Hard Way",file:"../audio/kanye-west/bully/tracks/hard-way.mp3",statId:"#BUL_HW"},
    {name:"Forever",file:"../audio/kanye-west/bully/tracks/forever.mp3",statId:"#BUL_FOR"},
    {name:"Champion 2",file:"../audio/kanye-west/bully/tracks/champion-2.mp3",statId:"#BUL_C2"},
    {name:"Empire",file:"../audio/kanye-west/bully/tracks/empire.mp3",statId:"#BUL_EMP"}
]},
{id:"die-lit",title:"Die Lit",artist:"Playboi Carti",year:"2018",type:"official",tags:["playboi carti","rap","2018"],cover:"https://upload.wikimedia.org/wikipedia/en/c/c6/Die_Lit_by_Playboi_Carti.jpg",tracks:[
    {name:"Long Time (Intro)",file:"../audio/playboi-carti/die-lit/tracks/long-time.mp3",statId:"#DL_LT"},
    {name:"R.I.P.",file:"../audio/playboi-carti/die-lit/tracks/rip.mp3",statId:"#DL_RIP"},
    {name:"Lean 4 Real (feat. Skepta)",file:"../audio/playboi-carti/die-lit/tracks/lean-4-real.mp3",statId:"#DL_L4R"},
    {name:"Old Money",file:"../audio/playboi-carti/die-lit/tracks/old-money.mp3",statId:"#DL_OM"},
    {name:"Love Hurts (feat. Travis Scott)",file:"../audio/playboi-carti/die-lit/tracks/love-hurts.mp3",statId:"#DL_LH"},
    {name:"Shoota (feat. Lil Uzi Vert)",file:"../audio/playboi-carti/die-lit/tracks/shoota.mp3",statId:"#DL_SHOOT"},
    {name:"Right Now (feat. Pi'erre Bourne)",file:"../audio/playboi-carti/die-lit/tracks/right-now.mp3",statId:"#DL_RN"},
    {name:"Poke It Out (feat. Nicki Minaj)",file:"../audio/playboi-carti/die-lit/tracks/poke-it-out.mp3",statId:"#DL_PIO"},
    {name:"Home (KOD)",file:"../audio/playboi-carti/die-lit/tracks/home-kod.mp3",statId:"#DL_HOME"},
    {name:"Fell In Luv (feat. Bryson Tiller)",file:"../audio/playboi-carti/die-lit/tracks/fell-in-luv.mp3",statId:"#DL_FIL"},
    {name:"Foreign",file:"../audio/playboi-carti/die-lit/tracks/foreign.mp3",statId:"#DL_FOR"},
    {name:"Pull Up",file:"../audio/playboi-carti/die-lit/tracks/pull-up.mp3",statId:"#DL_PU"},
    {name:"Mileage (feat. Chief Keef)",file:"../audio/playboi-carti/die-lit/tracks/mileage.mp3",statId:"#DL_MIL"},
    {name:"FlatBed Freestyle",file:"../audio/playboi-carti/die-lit/tracks/flatbed-freestyle.mp3",statId:"#DL_FF"},
    {name:"No Time (feat. Gunna)",file:"../audio/playboi-carti/die-lit/tracks/no-time.mp3",statId:"#DL_NT"},
    {name:"Middle of the Summer (feat. Red Coldhearted)",file:"../audio/playboi-carti/die-lit/tracks/middle-of-the-summer.mp3",statId:"#DL_MOTS"},
    {name:"Choppa Won't Miss (feat. Young Thug)",file:"../audio/playboi-carti/die-lit/tracks/choppa-wont-miss.mp3",statId:"#DL_CWM"},
    {name:"R.I.P. Fredo (Notice Me) (feat. Young Nudy)",file:"../audio/playboi-carti/die-lit/tracks/rip-fredo.mp3",statId:"#DL_RIPF"},
    {name:"Top (feat. Pi'erre Bourne)",file:"../audio/playboi-carti/die-lit/tracks/top.mp3",statId:"#DL_TOP"}
]},
{
  id: "goblin",
  title: "Goblin",
  artist: "Tyler, the Creator",
  year: "2011",
  type: "official",
  tags: ["tyler the creator","rap","2011"],
  cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/goblin/covers/IMG_6377.jpeg",
  tracks: [
    {name:"Goblin",file:"../audio/tyler-the-creator/goblin/tracks/goblin.mp3",statId:"#GOB_GOB"},
    {name:"Yonkers",file:"../audio/tyler-the-creator/goblin/tracks/yonkers.mp3",statId:"#GOB_YON"},
    {name:"Radicals",file:"../audio/tyler-the-creator/goblin/tracks/radicals.mp3",statId:"#GOB_RAD"},
    {name:"She (feat. Frank Ocean)",file:"../audio/tyler-the-creator/goblin/tracks/she.mp3",statId:"#GOB_SHE"},
    {name:"Transylvania",file:"../audio/tyler-the-creator/goblin/tracks/transylvania.mp3",statId:"#GOB_TRANS"},
    {name:"Nightmare",file:"../audio/tyler-the-creator/goblin/tracks/nightmare.mp3",statId:"#GOB_NIGHT"},
    {name:"Tron Cat",file:"../audio/tyler-the-creator/goblin/tracks/tron-cat.mp3",statId:"#GOB_TC"},
    {name:"Her",file:"../audio/tyler-the-creator/goblin/tracks/her.mp3",statId:"#GOB_HER"},
    {name:"Sandwitches (feat. Hodgy)",file:"../audio/tyler-the-creator/goblin/tracks/sandwitches.mp3",statId:"#GOB_SAND"},
    {name:"Fish",file:"../audio/tyler-the-creator/goblin/tracks/fish.mp3",statId:"#GOB_FISH"},
    {name:"Analog (feat. Hodgy)",file:"../audio/tyler-the-creator/goblin/tracks/analog.mp3",statId:"#GOB_ANA"},
    {name:"B.S.D.",file:"../audio/tyler-the-creator/goblin/tracks/bsd.mp3",statId:"#GOB_BSD"},
    {name:"Window (feat. Domo Genesis, Hodgy & Mike G)",file:"../audio/tyler-the-creator/goblin/tracks/window.mp3",statId:"#GOB_WIN"},
    {name:"AU79",file:"../audio/tyler-the-creator/goblin/tracks/au79.mp3",statId:"#GOB_AU79"},
    {name:"Golden",file:"../audio/tyler-the-creator/goblin/tracks/golden.mp3",statId:"#GOB_GOLD"}
  ]
},
{
  id: "wolf",
  title: "Wolf",
  artist: "Tyler, the Creator",
  year: "2013",
  type: "official",
  tags: ["tyler the creator","rap","2013"],
  cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/wolf/covers/IMG_6378.jpeg",
  tracks: [
    {name:"Wolf",file:"../audio/tyler-the-creator/wolf/tracks/wolf.mp3",statId:"#WOLF_WOLF"},
    {name:"Jamba (feat. Hodgy)",file:"../audio/tyler-the-creator/wolf/tracks/jamba.mp3",statId:"#WOLF_JAM"},
    {name:"Cowboy",file:"../audio/tyler-the-creator/wolf/tracks/cowboy.mp3",statId:"#WOLF_COW"},
    {name:"Awkward",file:"../audio/tyler-the-creator/wolf/tracks/awkward.mp3",statId:"#WOLF_AWK"},
    {name:"Domo23",file:"../audio/tyler-the-creator/wolf/tracks/domo23.mp3",statId:"#WOLF_D23"},
    {name:"Answer",file:"../audio/tyler-the-creator/wolf/tracks/answer.mp3",statId:"#WOLF_ANS"},
    {name:"Slater (feat. Frank Ocean)",file:"../audio/tyler-the-creator/wolf/tracks/slater.mp3",statId:"#WOLF_SLA"},
    {name:"48",file:"../audio/tyler-the-creator/wolf/tracks/48.mp3",statId:"#WOLF_48"},
    {name:"Colossus",file:"../audio/tyler-the-creator/wolf/tracks/colossus.mp3",statId:"#WOLF_COL"},
    {name:"PartyIsntOver/Campfire/Bimmer (feat. Frank Ocean & Lætitia Sadier)",file:"../audio/tyler-the-creator/wolf/tracks/piocb.mp3",statId:"#WOLF_PCB"},
    {name:"IFHY (feat. Pharrell)",file:"../audio/tyler-the-creator/wolf/tracks/ifhy.mp3",statId:"#WOLF_IFHY"},
    {name:"Pigs",file:"../audio/tyler-the-creator/wolf/tracks/pigs.mp3",statId:"#WOLF_PIGS"},
    {name:"Parking Lot (feat. Mike G & Casey Veggies)",file:"../audio/tyler-the-creator/wolf/tracks/parking-lot.mp3",statId:"#WOLF_PL"},
    {name:"Rusty (feat. Domo Genesis & Earl Sweatshirt)",file:"../audio/tyler-the-creator/wolf/tracks/rusty.mp3",statId:"#WOLF_RUS"},
    {name:"Trashwang (feat. Odd Future)",file:"../audio/tyler-the-creator/wolf/tracks/trashwang.mp3",statId:"#WOLF_TW"},
    {name:"Treehome95 (feat. Coco O. & Erykah Badu)",file:"../audio/tyler-the-creator/wolf/tracks/treehome95.mp3",statId:"#WOLF_TH95"},
    {name:"Tamale",file:"../audio/tyler-the-creator/wolf/tracks/tamale.mp3",statId:"#WOLF_TAM"},
    {name:"Lone",file:"../audio/tyler-the-creator/wolf/tracks/lone.mp3",statId:"#WOLF_LONE"}
  ]
},
{
  id: "cherry-bomb",
  title: "Cherry Bomb",
  artist: "Tyler, the Creator",
  year: "2015",
  type: "official",
  tags: ["tyler the creator","rap","2015"],
  cover: "https://preview.redd.it/qubhiqn6zrs51.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=a4129b25a29105c59a9a9ea5d866ae8cd8f2915d",
  tracks: [
    {name:"Deathcamp",file:"../audio/tyler-the-creator/cherry-bomb/tracks/deathcamp.mp3",statId:"#CB_DC"},
    {name:"Buffalo",file:"../audio/tyler-the-creator/cherry-bomb/tracks/buffalo.mp3",statId:"#CB_BUF"},
    {name:"Pilot",file:"../audio/tyler-the-creator/cherry-bomb/tracks/pilot.mp3",statId:"#CB_PIL"},
    {name:"Run",file:"../audio/tyler-the-creator/cherry-bomb/tracks/run.mp3",statId:"#CB_RUN"},
    {name:"Find Your Wings (feat. Kali Uchis & Roy Ayers)",file:"../audio/tyler-the-creator/cherry-bomb/tracks/find-your-wings.mp3",statId:"#CB_FYW"},
    {name:"Cherry Bomb",file:"../audio/tyler-the-creator/cherry-bomb/tracks/cherry-bomb.mp3",statId:"#CB_CB"},
    {name:"Blow My Load (feat. Wanya Morris, Dâm-Funk & Austin Feinstein)",file:"../audio/tyler-the-creator/cherry-bomb/tracks/blow-my-load.mp3",statId:"#CB_BML"},
    {name:"2SEATER (feat. Aaron Shaw & Samantha Nelson)",file:"../audio/tyler-the-creator/cherry-bomb/tracks/2seater.mp3",statId:"#CB_2S"},
    {name:"The Brown Stains of Darkeese Latifah Part 6–12 (Remix) (feat. Schoolboy Q)",file:"../audio/tyler-the-creator/cherry-bomb/tracks/brown-stains.mp3",statId:"#CB_BS"},
    {name:"Fucking Young / Perfect (feat. Charlie Wilson, Kali Uchis & Austin Feinstein)",file:"../audio/tyler-the-creator/cherry-bomb/tracks/fucking-young-perfect.mp3",statId:"#CB_FYP"},
    {name:"Smuckers (feat. Kanye West & Lil Wayne)",file:"../audio/tyler-the-creator/cherry-bomb/tracks/smuckers.mp3",statId:"#CB_SMU"},
    {name:"Keep Da O's (feat. Pharrell & Coco O.)",file:"../audio/tyler-the-creator/cherry-bomb/tracks/keep-da-os.mp3",statId:"#CB_KDO"},
    {name:"Okaga, CA",file:"../audio/tyler-the-creator/cherry-bomb/tracks/okaga-ca.mp3",statId:"#CB_OKA"}
  ]
},
{
  id: "flower-boy",
  title: "Flower Boy",
  artist: "Tyler, the Creator",
  year: "2017",
  type: "official",
  tags: ["tyler the creator","rap","2017"],
  cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/flowerboy/covers/IMG_6382.jpeg",
  tracks: [
    {name:"Foreword (feat. Rex Orange County)",file:"../audio/tyler-the-creator/flower-boy/tracks/foreword.mp3",statId:"#FB_FORE"},
    {name:"Where This Flower Blooms (feat. Frank Ocean)",file:"../audio/tyler-the-creator/flower-boy/tracks/where-this-flower-blooms.mp3",statId:"#FB_WTFB"},
    {name:"Sometimes...",file:"../audio/tyler-the-creator/flower-boy/tracks/sometimes.mp3",statId:"#FB_SOM"},
    {name:"See You Again (feat. Kali Uchis)",file:"../audio/tyler-the-creator/flower-boy/tracks/see-you-again.mp3",statId:"#FB_SYA"},
    {name:"Who Dat Boy (feat. A$AP Rocky)",file:"../audio/tyler-the-creator/flower-boy/tracks/who-dat-boy.mp3",statId:"#FB_WDB"},
    {name:"Pothole (feat. Jaden Smith)",file:"../audio/tyler-the-creator/flower-boy/tracks/pothole.mp3",statId:"#FB_POT"},
    {name:"Garden Shed (feat. Estelle)",file:"../audio/tyler-the-creator/flower-boy/tracks/garden-shed.mp3",statId:"#FB_GS"},
    {name:"Boredom (feat. Rex Orange County & Anna of the North)",file:"../audio/tyler-the-creator/flower-boy/tracks/boredom.mp3",statId:"#FB_BOR"},
    {name:"I Ain't Got Time!",file:"../audio/tyler-the-creator/flower-boy/tracks/i-aint-got-time.mp3",statId:"#FB_IAGT"},
    {name:"911 / Mr. Lonely (feat. Frank Ocean & Steve Lacy)",file:"../audio/tyler-the-creator/flower-boy/tracks/911-mr-lonely.mp3",statId:"#FB_911"},
    {name:"Droppin' Seeds (feat. Lil Wayne)",file:"../audio/tyler-the-creator/flower-boy/tracks/droppin-seeds.mp3",statId:"#FB_DS"},
    {name:"November",file:"../audio/tyler-the-creator/flower-boy/tracks/november.mp3",statId:"#FB_NOV"},
    {name:"Glitter",file:"../audio/tyler-the-creator/flower-boy/tracks/glitter.mp3",statId:"#FB_GLI"},
    {name:"Enjoy Right Now, Today",file:"../audio/tyler-the-creator/flower-boy/tracks/enjoy-right-now-today.mp3",statId:"#FB_ERNT"}
  ]
},
{
  id: "igor",
  title: "IGOR",
  artist: "Tyler, the Creator",
  year: "2019",
  type: "official",
  tags: ["tyler the creator", "rap", "2019", "alternative hip hop"],
  cover: "https://upload.wikimedia.org/wikipedia/en/5/51/Igor_-_Tyler%2C_the_Creator.jpg",
  tracks: [
    {name:"IGOR'S THEME",file:"../audio/tyler-the-creator/igor/tracks/igors-theme.mp3",statId:"#IGOR_IT"},
    {name:"EARFQUAKE",file:"../audio/tyler-the-creator/igor/tracks/earfquake.mp3",statId:"#IGOR_EQ"},
    {name:"I THINK",file:"../audio/tyler-the-creator/igor/tracks/i-think.mp3",statId:"#IGOR_ITK"},
    {name:"EXACTLY WHAT YOU RUN FROM YOU END UP CHASING",file:"../audio/tyler-the-creator/igor/tracks/exactly-what-you-run-from.mp3",statId:"#IGOR_EWYRF"},
    {name:"RUNNING OUT OF TIME",file:"../audio/tyler-the-creator/igor/tracks/running-out-of-time.mp3",statId:"#IGOR_ROOT"},
    {name:"NEW MAGIC WAND",file:"../audio/tyler-the-creator/igor/tracks/new-magic-wand.mp3",statId:"#IGOR_NMW"},
    {name:"A BOY IS A GUN*",file:"../audio/tyler-the-creator/igor/tracks/a-boy-is-a-gun.mp3",statId:"#IGOR_ABIAG"},
    {name:"PUPPET",file:"../audio/tyler-the-creator/igor/tracks/puppet.mp3",statId:"#IGOR_PUP"},
    {name:"WHAT'S GOOD",file:"../audio/tyler-the-creator/igor/tracks/whats-good.mp3",statId:"#IGOR_WG"},
    {name:"GONE, GONE / THANK YOU",file:"../audio/tyler-the-creator/igor/tracks/gone-gone-thank-you.mp3",statId:"#IGOR_GGTY"},
    {name:"I DON'T LOVE YOU ANYMORE",file:"../audio/tyler-the-creator/igor/tracks/idlya.mp3",statId:"#IGOR_IDLYA"},
    {name:"ARE WE STILL FRIENDS?",file:"../audio/tyler-the-creator/igor/tracks/are-we-still-friends.mp3",statId:"#IGOR_AWSF"}
  ]
},
{
  id: "cmiygl",
  title: "CALL ME IF YOU GET LOST",
  artist: "Tyler, the Creator",
  year: "2021",
  type: "official",
  tags: ["tyler the creator","rap","2021"],
  cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/cmiygl/covers/IMG_6383.jpeg",
  tracks: [
    {name:"SIR BAUDELAIRE (feat. DJ Drama)",file:"../audio/tyler-the-creator/cmiygl/tracks/sir-baudelaire.mp3",statId:"#CMIYGL_SB"},
    {name:"CORSO",file:"../audio/tyler-the-creator/cmiygl/tracks/corso.mp3",statId:"#CMIYGL_COR"},
    {name:"LEMONHEAD (feat. 42 Dugg)",file:"../audio/tyler-the-creator/cmiygl/tracks/lemonhead.mp3",statId:"#CMIYGL_LEM"},
    {name:"WUSYANAME (feat. YoungBoy Never Broke Again & Ty Dolla $ign)",file:"../audio/tyler-the-creator/cmiygl/tracks/wusyaname.mp3",statId:"#CMIYGL_WUS"},
    {name:"LUMBERJACK",file:"../audio/tyler-the-creator/cmiygl/tracks/lumberjack.mp3",statId:"#CMIYGL_LUM"},
    {name:"HOT WIND BLOWS (feat. Lil Wayne)",file:"../audio/tyler-the-creator/cmiygl/tracks/hot-wind-blows.mp3",statId:"#CMIYGL_HWB"},
    {name:"MASSA",file:"../audio/tyler-the-creator/cmiygl/tracks/massa.mp3",statId:"#CMIYGL_MAS"},
    {name:"RUNITUP (feat. Teezo Touchdown)",file:"../audio/tyler-the-creator/cmiygl/tracks/runitup.mp3",statId:"#CMIYGL_RUN"},
    {name:"MANIFESTO (feat. Domo Genesis)",file:"../audio/tyler-the-creator/cmiygl/tracks/manifesto.mp3",statId:"#CMIYGL_MAN"},
    {name:"SWEET / I THOUGHT YOU WANTED TO DANCE (feat. Brent Faiyaz & Fana Hues)",file:"../audio/tyler-the-creator/cmiygl/tracks/sweet-itywtd.mp3",statId:"#CMIYGL_SWE"},
    {name:"MOMMA TALK",file:"../audio/tyler-the-creator/cmiygl/tracks/momma-talk.mp3",statId:"#CMIYGL_MT"},
    {name:"RISE! (feat. Daisy World)",file:"../audio/tyler-the-creator/cmiygl/tracks/rise.mp3",statId:"#CMIYGL_RISE"},
    {name:"BLESSED",file:"../audio/tyler-the-creator/cmiygl/tracks/blessed.mp3",statId:"#CMIYGL_BLE"},
    {name:"JUGGERNAUT (feat. Lil Uzi Vert & Pharrell Williams)",file:"../audio/tyler-the-creator/cmiygl/tracks/juggernaut.mp3",statId:"#CMIYGL_JUG"},
    {name:"WILSHIRE",file:"../audio/tyler-the-creator/cmiygl/tracks/wilshire.mp3",statId:"#CMIYGL_WIL"},
    {name:"SAFARI",file:"../audio/tyler-the-creator/cmiygl/tracks/safari.mp3",statId:"#CMIYGL_SAF"}
  ]
},
{
  id: "cmiygl-deluxe",
  title: "CALL ME IF YOU GET LOST: The Estate Sale",
  artist: "Tyler, the Creator",
  year: "2023",
  type: "official",
  tags: ["tyler the creator","rap","2023","deluxe"],
  cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/cmiygl_the-estate-sale/covers/IMG_6384.jpeg",
  tracks: [
    {name:"EVERYTHING MUST GO (feat. DJ Drama)",file:"../audio/tyler-the-creator/cmiygl_the-estate-sale/everything-must-go.mp3",statId:"#TES_EMG"},
    {name:"STUNTMAN (feat. Vince Staples)",file:"../audio/tyler-the-creator/cmiygl_the-estate-sale/stuntman.mp3",statId:"#TES_STU"},
    {name:"WHAT A DAY",file:"../audio/tyler-the-creator/cmiygl_the-estate-sale/what-a-day.mp3",statId:"#TES_WAD"},
    {name:"WHARF TALK (feat. A$AP Rocky)",file:"../audio/tyler-the-creator/cmiygl_the-estate-sale/wharf-talk.mp3",statId:"#TES_WT"},
    {name:"DOGTOOTH",file:"../audio/tyler-the-creator/cmiygl_the-estate-sale/dogtooth.mp3",statId:"#TES_DOG"},
    {name:"HEAVEN TO ME",file:"../audio/tyler-the-creator/cmiygl_the-estate-sale/heaven-to-me.mp3",statId:"#TES_HTM"},
    {name:"BOYFRIEND, GIRLFRIEND (2020 Demo) (feat. YG)",file:"../audio/tyler-the-creator/cmiygl_the-estate-sale/boyfriend-girlfriend.mp3",statId:"#TES_BG"}
  ]
},
{
  id: "chromakopia",
  title: "CHROMAKOPIA",
  artist: "Tyler, the Creator",
  year: "2024",
  type: "official",
  tags: ["tyler the creator","rap","2024"],
  cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/chromakopia/covers/IMG_6385.webp",
  tracks: [
    {name:"ST. CHROMA",file:"../audio/tyler-the-creator/chromakopia/st-chroma.mp3",statId:"#CHK_SC"},
    {name:"NOID",file:"../audio/tyler-the-creator/chromakopia/noid.mp3",statId:"#CHK_NOID"},
    {name:"I KILLED YOU",file:"../audio/tyler-the-creator/chromakopia/i-killed-you.mp3",statId:"#CHK_IKY"},
    {name:"THOUGHT I WAS DEAD",file:"../audio/tyler-the-creator/chromakopia/thought-i-was-dead.mp3",statId:"#CHK_TWD"},
    {name:"LIKE HIM",file:"../audio/tyler-the-creator/chromakopia/like-him.mp3",statId:"#CHK_LH"},
    {name:"DARLING, I",file:"../audio/tyler-the-creator/chromakopia/darling-i.mp3",statId:"#CHK_DI"},
    {name:"HEY JANE",file:"../audio/tyler-the-creator/chromakopia/hey-jane.mp3",statId:"#CHK_HJ"},
    {name:"BALLOON",file:"../audio/tyler-the-creator/chromakopia/balloon.mp3",statId:"#CHK_BAL"},
    {name:"LOVE, PEACE, AND LIGHT",file:"../audio/tyler-the-creator/chromakopia/love-peace-light.mp3",statId:"#CHK_LPL"},
    {name:"WELCOME TO THE DISCO",file:"../audio/tyler-the-creator/chromakopia/welcome-to-the-disco.mp3",statId:"#CHK_WTD"},
    {name:"ELECTRIC RAINBOW",file:"../audio/tyler-the-creator/chromakopia/electric-rainbow.mp3",statId:"#CHK_ER"},
    {name:"FANTASY",file:"../audio/tyler-the-creator/chromakopia/fantasy.mp3",statId:"#CHK_FAN"},
    {name:"CHROMAKOPIA (Outro)",file:"../audio/tyler-the-creator/chromakopia/chromakopia-outro.mp3",statId:"#CHK_OUT"}
  ]
},
{
  id: "dont-tap-the-glass",
  title: "DON'T TAP THE GLASS",
  artist: "Tyler, the Creator",
  year: "2025",
  type: "official",
  tags: ["tyler the creator","rap","2025"],
  cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/dont-tap-the-glass/covers/Untitled174_20260225160356.png",
  tracks: [
    {name:"Big Poe (feat. Sk8brd)",file:"../audio/tyler-the-creator/dont-tap-the-glass/tracks/big-poe.mp3",statId:"#DTTG_BP"},
    {name:"Sugar On My Tongue",file:"../audio/tyler-the-creator/dont-tap-the-glass/tracks/sugar-on-my-tongue.mp3",statId:"#DTTG_SOT"},
    {name:"Sucka Free",file:"../audio/tyler-the-creator/dont-tap-the-glass/tracks/sucka-free.mp3",statId:"#DTTG_SF"},
    {name:"Mommanem",file:"../audio/tyler-the-creator/dont-tap-the-glass/tracks/mommanem.mp3",statId:"#DTTG_MOM"},
    {name:"Stop Playing With Me",file:"../audio/tyler-the-creator/dont-tap-the-glass/tracks/stop-playing-with-me.mp3",statId:"#DTTG_SPWM"},
    {name:"Ring Ring Ring",file:"../audio/tyler-the-creator/dont-tap-the-glass/tracks/ring-ring-ring.mp3",statId:"#DTTG_RRR"},
    {name:"Don't Tap That Glass / Tweakin'",file:"../audio/tyler-the-creator/dont-tap-the-glass/tracks/dont-tap-that-glass-tweakin.mp3",statId:"#DTTG_DTT"},
    {name:"Don't You Worry Baby",file:"../audio/tyler-the-creator/dont-tap-the-glass/tracks/dont-you-worry-baby.mp3",statId:"#DTTG_DYWB"},
    {name:"I'll Take Care of You",file:"../audio/tyler-the-creator/dont-tap-the-glass/tracks/ill-take-care-of-you.mp3",statId:"#DTTG_ITCOY"},
    {name:"Tell Me What It Is",file:"../audio/tyler-the-creator/dont-tap-the-glass/tracks/tell-me-what-it-is.mp3",statId:"#DTTG_TMWII"}
  ]
},
{
  id: "section-80",
  title: "Section.80",
  artist: "Kendrick Lamar",
  year: "2011",
  type: "official",
  tags: ["kendrick lamar","rap","2011","conscious hip hop"],
  cover: "https://upload.wikimedia.org/wikipedia/en/thumb/4/48/Section.80-Cover.jpg/250px-Section.80-Cover.jpg",
  tracks: [
    {name:"Fuck Your Ethnicity",file:"../audio/kendrick-lamar/section-80/tracks/fuck-your-ethnicity.mp3",statId:"#S80_FYE"},
    {name:"Hol' Up",file:"../audio/kendrick-lamar/section-80/tracks/hol-up.mp3",statId:"#S80_HU"},
    {name:"A.D.H.D",file:"../audio/kendrick-lamar/section-80/tracks/adhd.mp3",statId:"#S80_ADHD"},
    {name:"No Make-Up (Her Vice) (feat. Colin Munroe)",file:"../audio/kendrick-lamar/section-80/tracks/no-makeup.mp3",statId:"#S80_NMU"},
    {name:"Tammy's Song (Her Evils)",file:"../audio/kendrick-lamar/section-80/tracks/tammys-song.mp3",statId:"#S80_TS"},
    {name:"Chapter Six",file:"../audio/kendrick-lamar/section-80/tracks/chapter-six.mp3",statId:"#S80_C6"},
    {name:"Ronald Reagan Era (His Evils)",file:"../audio/kendrick-lamar/section-80/tracks/ronald-reagan-era.mp3",statId:"#S80_RRE"},
    {name:"Poe Man's Dreams (His Vice) (feat. GLC)",file:"../audio/kendrick-lamar/section-80/tracks/poe-mans-dreams.mp3",statId:"#S80_PMD"},
    {name:"The Spiteful Chant (feat. Schoolboy Q)",file:"../audio/kendrick-lamar/section-80/tracks/the-spiteful-chant.mp3",statId:"#S80_TSC"},
    {name:"Chapter Ten",file:"../audio/kendrick-lamar/section-80/tracks/chapter-ten.mp3",statId:"#S80_C10"},
    {name:"Keisha's Song (Her Pain) (feat. Ashtrobot)",file:"../audio/kendrick-lamar/section-80/tracks/keishas-song.mp3",statId:"#S80_KS"},
    {name:"Rigamortus",file:"../audio/kendrick-lamar/section-80/tracks/rigamortus.mp3",statId:"#S80_RIG"},
    {name:"Kush & Corinthians (His Pain) (feat. BJ the Chicago Kid)",file:"../audio/kendrick-lamar/section-80/tracks/kush-corinthians.mp3",statId:"#S80_KC"},
    {name:"Blow My High (Members Only)",file:"../audio/kendrick-lamar/section-80/tracks/blow-my-high.mp3",statId:"#S80_BMH"},
    {name:"Ab-Soul's Outro (feat. Ab-Soul)",file:"../audio/kendrick-lamar/section-80/tracks/ab-souls-outro.mp3",statId:"#S80_ASO"},
    {name:"HiiiPower",file:"../audio/kendrick-lamar/section-80/tracks/hiiipower.mp3",statId:"#S80_HP"}
  ]
},
{
  id: "good-kid-maad-city",
  title: "good kid, m.A.A.d city",
  artist: "Kendrick Lamar",
  year: "2012",
  type: "official",
  tags: ["kendrick lamar","rap","2012","west coast hip hop"],
  cover: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgFRLKqN8J5PnVQaBUTENfIWH9W72_qInvDA&s",
  tracks: [
    {name:"Sherane a.k.a Master Splinter's Daughter",file:"../audio/kendrick-lamar/good-kid-maad-city/tracks/sherane.mp3",statId:"#GKMC_S"},
    {name:"Bitch, Don't Kill My Vibe",file:"../audio/kendrick-lamar/good-kid-maad-city/tracks/bdkmv.mp3",statId:"#GKMC_BDKMV"},
    {name:"Backseat Freestyle",file:"../audio/kendrick-lamar/good-kid-maad-city/tracks/backseat-freestyle.mp3",statId:"#GKMC_BF"},
    {name:"The Art of Peer Pressure",file:"../audio/kendrick-lamar/good-kid-maad-city/tracks/art-of-peer-pressure.mp3",statId:"#GKMC_AOPP"},
    {name:"Money Trees (feat. Jay Rock)",file:"../audio/kendrick-lamar/good-kid-maad-city/tracks/money-trees.mp3",statId:"#GKMC_MT"},
    {name:"Poetic Justice (feat. Drake)",file:"../audio/kendrick-lamar/good-kid-maad-city/tracks/poetic-justice.mp3",statId:"#GKMC_PJ"},
    {name:"good kid",file:"../audio/kendrick-lamar/good-kid-maad-city/tracks/good-kid.mp3",statId:"#GKMC_GK"},
    {name:"m.A.A.d city (feat. MC Eiht)",file:"../audio/kendrick-lamar/good-kid-maad-city/tracks/maad-city.mp3",statId:"#GKMC_MC"},
    {name:"Swimming Pools (Drank)",file:"../audio/kendrick-lamar/good-kid-maad-city/tracks/swimming-pools.mp3",statId:"#GKMC_SP"},
    {name:"Sing About Me, I'm Dying of Thirst",file:"../audio/kendrick-lamar/good-kid-maad-city/tracks/samidot.mp3",statId:"#GKMC_SAM"},
    {name:"Real (feat. Anna Wise)",file:"../audio/kendrick-lamar/good-kid-maad-city/tracks/real.mp3",statId:"#GKMC_REAL"},
    {name:"Compton (feat. Dr. Dre)",file:"../audio/kendrick-lamar/good-kid-maad-city/tracks/compton.mp3",statId:"#GKMC_COMP"}
  ]
},
{
  id: "to-pimp-a-butterfly",
  title: "To Pimp a Butterfly",
  artist: "Kendrick Lamar",
  year: "2015",
  type: "official",
  tags: ["kendrick lamar","rap","2015","jazz rap"],
  cover: "https://upload.wikimedia.org/wikipedia/en/f/f6/Kendrick_Lamar_-_To_Pimp_a_Butterfly.png",
  tracks: [
    {name:"Wesley's Theory (feat. George Clinton & Thundercat)",file:"../audio/kendrick-lamar/to-pimp-a-butterfly/tracks/wesleys-theory.mp3",statId:"#TPAB_WT"},
    {name:"For Free? (Interlude)",file:"../audio/kendrick-lamar/to-pimp-a-butterfly/tracks/for-free.mp3",statId:"#TPAB_FF"},
    {name:"King Kunta",file:"../audio/kendrick-lamar/to-pimp-a-butterfly/tracks/king-kunta.mp3",statId:"#TPAB_KK"},
    {name:"Institutionalized",file:"../audio/kendrick-lamar/to-pimp-a-butterfly/tracks/institutionalized.mp3",statId:"#TPAB_INST"},
    {name:"These Walls",file:"../audio/kendrick-lamar/to-pimp-a-butterfly/tracks/these-walls.mp3",statId:"#TPAB_TW"},
    {name:"u",file:"../audio/kendrick-lamar/to-pimp-a-butterfly/tracks/u.mp3",statId:"#TPAB_U"},
    {name:"Alright",file:"../audio/kendrick-lamar/to-pimp-a-butterfly/tracks/alright.mp3",statId:"#TPAB_ALR"},
    {name:"Mortal Man",file:"../audio/kendrick-lamar/to-pimp-a-butterfly/tracks/mortal-man.mp3",statId:"#TPAB_MM"}
  ]
},
{
  id: "damn",
  title: "DAMN.",
  artist: "Kendrick Lamar",
  year: "2017",
  type: "official",
  tags: ["kendrick lamar","rap","2017"],
  cover: "https://external-preview.redd.it/7x4J7CpDkmARyvMW94fO6hSU2ohEztso2jzO37emeR8.jpg?auto=webp&s=cfc96f803045b54357f0824e59a3dd83aeec0389",
  tracks: [
    {name:"BLOOD.",file:"../audio/kendrick-lamar/damn/tracks/blood.mp3",statId:"#DAMN_BLOOD"},
    {name:"DNA.",file:"../audio/kendrick-lamar/damn/tracks/dna.mp3",statId:"#DAMN_DNA"},
    {name:"HUMBLE.",file:"../audio/kendrick-lamar/damn/tracks/humble.mp3",statId:"#DAMN_HUMBLE"},
    {name:"DUCKWORTH.",file:"../audio/kendrick-lamar/damn/tracks/duckworth.mp3",statId:"#DAMN_DUCK"}
  ]
},
{
  id: "eternal-atake",
  title: "Eternal Atake",
  artist: "Lil Uzi Vert",
  year: "2020",
  type: "official",
  tags: ["lil uzi vert","rap","2020"],
  cover: "https://i.ebayimg.com/images/g/9ToAAOSwJB5ksb0W/s-l1200.jpg",
  tracks: [
    {name:"Baby Pluto",file:"../audio/lil-uzi-vert/eternal-atake/tracks/baby_pluto.mp3",statId:"#EA_BABY_PLUTO"},
    {name:"Lo Mein",file:"../audio/lil-uzi-vert/eternal-atake/tracks/lo_mein.mp3",statId:"#EA_LO_MEIN"},
    {name:"Silly Watch",file:"../audio/lil-uzi-vert/eternal-atake/tracks/silly_watch.mp3",statId:"#EA_SILLY_WATCH"},
    {name:"POP",file:"../audio/lil-uzi-vert/eternal-atake/tracks/pop.mp3",statId:"#EA_POP"},
    {name:"You Better Move",file:"../audio/lil-uzi-vert/eternal-atake/tracks/you_better_move.mp3",statId:"#EA_YBM"},
    {name:"Homecoming",file:"../audio/lil-uzi-vert/eternal-atake/tracks/homecoming.mp3",statId:"#EA_HOMECOMING"},
    {name:"I Can Show You",file:"../audio/lil-uzi-vert/eternal-atake/tracks/i_can_show_you.mp3",statId:"#EA_ICSY"},
    {name:"Venetia",file:"../audio/lil-uzi-vert/eternal-atake/tracks/venetia.mp3",statId:"#EA_VENETIA"},
    {name:"Secure the Bag",file:"../audio/lil-uzi-vert/eternal-atake/tracks/secure_the_bag.mp3",statId:"#EA_STB"},
    {name:"Prices",file:"../audio/lil-uzi-vert/eternal-atake/tracks/prices.mp3",statId:"#EA_PRICES"},
    {name:"Urgency (feat. Syd)",file:"../audio/lil-uzi-vert/eternal-atake/tracks/urgency.mp3",statId:"#EA_URGENCY"},
    {name:"Celebration Station",file:"../audio/lil-uzi-vert/eternal-atake/tracks/celebration_station.mp3",statId:"#EA_CSTATION"},
    {name:"Bigger Than Life",file:"../audio/lil-uzi-vert/eternal-atake/tracks/bigger_than_life.mp3",statId:"#EA_BTL"},
    {name:"Chrome Heart Tags",file:"../audio/lil-uzi-vert/eternal-atake/tracks/chrome_heart_tags.mp3",statId:"#EA_CHT"},
    {name:"Bust Me",file:"../audio/lil-uzi-vert/eternal-atake/tracks/bust_me.mp3",statId:"#EA_BUST_ME"},
    {name:"That Way",file:"../audio/lil-uzi-vert/eternal-atake/tracks/that_way.mp3",statId:"#EA_THAT_WAY"},
    {name:"P2",file:"../audio/lil-uzi-vert/eternal-atake/tracks/p2.mp3",statId:"#EA_P2"}
  ]
},
{
  id: "luv_is_rage",
  title: "Luv Is Rage",
  artist: "Lil Uzi Vert",
  year: "2015",
  type: "official",
  tags: ["lil uzi vert","rap","2015"],
  cover: "https://upload.wikimedia.org/wikipedia/en/thumb/5/54/Luv_Is_Rage_Cover.jpg/250px-Luv_Is_Rage_Cover.jpg",
  tracks: [
    {name:"Safe House",file:"../audio/lil-uzi-vert/luv_is_rage/tracks/safe_house.mp3",statId:"#LIR_SAFE_HOUSE"},
    {name:"Enemies",file:"../audio/lil-uzi-vert/luv_is_rage/tracks/enemies.mp3",statId:"#LIR_ENEMIES"},
    {name:"Want Some More",file:"../audio/lil-uzi-vert/luv_is_rage/tracks/want_some_more.mp3",statId:"#LIR_WSM"},
    {name:"Right Now",file:"../audio/lil-uzi-vert/luv_is_rage/tracks/right_now.mp3",statId:"#LIR_RIGHT_NOW"},
    {name:"All My Chains",file:"../audio/lil-uzi-vert/luv_is_rage/tracks/all_my_chains.mp3",statId:"#LIR_AMC"},
    {name:"Nuyork Nights at 21",file:"../audio/lil-uzi-vert/luv_is_rage/tracks/nuyork_nights.mp3",statId:"#LIR_NNY21"},
    {name:"Yamborghini Dream",file:"../audio/lil-uzi-vert/luv_is_rage/tracks/yamborghini_dream.mp3",statId:"#LIR_YAMB"},
    {name:"Bleed",file:"../audio/lil-uzi-vert/luv_is_rage/tracks/bleed.mp3",statId:"#LIR_BLEED"},
    {name:"Luv Is Rage",file:"../audio/lil-uzi-vert/luv_is_rage/tracks/luv_is_rage.mp3",statId:"#LIR_TITLE"}
  ]
},
{
  id: "luv_vs_the_world_2",
  title: "Luv vs. The World 2",
  artist: "Lil Uzi Vert",
  year: "2020",
  type: "official",
  tags: ["lil uzi vert","rap","2020"],
  cover: "https://upload.wikimedia.org/wikipedia/en/thumb/9/9b/Lil_Uzi_Vert_vs_the_World_2_cover_art.jpg/250px-Lil_Uzi_Vert_vs_the_World_2_cover_art.jpg",
  tracks: [
    {name:"Myron",file:"../audio/lil-uzi-vert/luv_vs_the_world_2/tracks/myron.mp3",statId:"#LVTW2_MYRON"},
    {name:"Lotus",file:"../audio/lil-uzi-vert/luv_vs_the_world_2/tracks/lotus.mp3",statId:"#LVTW2_LOTUS"},
    {name:"Bean (Kobe)",file:"../audio/lil-uzi-vert/luv_vs_the_world_2/tracks/bean_kobe.mp3",statId:"#LVTW2_BEAN"},
    {name:"Yessirskiii (feat. 21 Savage)",file:"../audio/lil-uzi-vert/luv_vs_the_world_2/tracks/yessirskiii.mp3",statId:"#LVTW2_YESSIR"},
    {name:"Wassup",file:"../audio/lil-uzi-vert/luv_vs_the_world_2/tracks/wassup.mp3",statId:"#LVTW2_WASSUP"},
    {name:"Strawberry Peels (feat. Young Thug & Gunna)",file:"../audio/lil-uzi-vert/luv_vs_the_world_2/tracks/strawberry_peels.mp3",statId:"#LVTW2_SP"},
    {name:"Moon Relate",file:"../audio/lil-uzi-vert/luv_vs_the_world_2/tracks/moon_relate.mp3",statId:"#LVTW2_MOON"},
    {name:"Come This Way",file:"../audio/lil-uzi-vert/luv_vs_the_world_2/tracks/come_this_way.mp3",statId:"#LVTW2_CTW"},
    {name:"Trap This Way (This Way)",file:"../audio/lil-uzi-vert/luv_vs_the_world_2/tracks/trap_this_way.mp3",statId:"#LVTW2_TTW"},
    {name:"Got the Guap (feat. Young Thug)",file:"../audio/lil-uzi-vert/luv_vs_the_world_2/tracks/got_the_guap.mp3",statId:"#LVTW2_GTG"},
    {name:"Leaders (feat. NAV)",file:"../audio/lil-uzi-vert/luv_vs_the_world_2/tracks/leaders.mp3",statId:"#LVTW2_LEADERS"},
    {name:"Baby Pluto",file:"../audio/lil-uzi-vert/luv_vs_the_world_2/tracks/baby_pluto.mp3",statId:"#LVTW2_BABY_PLUTO"},
    {name:"P2",file:"../audio/lil-uzi-vert/luv_vs_the_world_2/tracks/p2.mp3",statId:"#LVTW2_P2"}
  ]
},
{
  id: "lil_uzi_vert_vs_the_world",
  title: "Lil Uzi Vert vs. The World",
  artist: "Lil Uzi Vert",
  year: "2016",
  type: "official",
  tags: ["lil uzi vert","rap","2016"],
  cover: "https://upload.wikimedia.org/wikipedia/en/d/d5/LilUziVertVsTheWorld.jpg",
  tracks: [
    {name:"Canadian Goose",file:"../audio/lil-uzi-vert/lil_uzi_vert_vs_the_world/tracks/canadian_goose.mp3",statId:"#LUVTW_CANADA"},
    {name:"Hi Roller",file:"../audio/lil-uzi-vert/lil_uzi_vert_vs_the_world/tracks/hi_roller.mp3",statId:"#LUVTW_HIROLLER"},
    {name:"Money Longer",file:"../audio/lil-uzi-vert/lil_uzi_vert_vs_the_world/tracks/money_longer.mp3",statId:"#LUVTW_ML"},
    {name:"Ps & Qs",file:"../audio/lil-uzi-vert/lil_uzi_vert_vs_the_world/tracks/ps_and_qs.mp3",statId:"#LUVTW_PSQS"},
    {name:"You Was Right",file:"../audio/lil-uzi-vert/lil_uzi_vert_vs_the_world/tracks/you_was_right.mp3",statId:"#LUVTW_YWR"},
    {name:"Baby Are You Home",file:"../audio/lil-uzi-vert/lil_uzi_vert_vs_the_world/tracks/baby_are_you_home.mp3",statId:"#LUVTW_BAYH"},
    {name:"Scott and Ramona",file:"../audio/lil-uzi-vert/lil_uzi_vert_vs_the_world/tracks/scott_and_ramona.mp3",statId:"#LUVTW_SAR"},
    {name:"The Way Life Goes",file:"../audio/lil-uzi-vert/lil_uzi_vert_vs_the_world/tracks/the_way_life_goes.mp3",statId:"#LUVTW_TWLG"},
    {name:"For Real",file:"../audio/lil-uzi-vert/lil_uzi_vert_vs_the_world/tracks/for_real.mp3",statId:"#LUVTW_FORREAL"}
  ]
},
{
  id: "pink-tape",
  title: "Pink Tape",
  artist: "Lil Uzi Vert",
  year: "2023",
  type: "official",
  tags: ["lil uzi vert","rap","2023"],
  cover: "https://m.media-amazon.com/images/I/91mf0aFkILL._UF1000,1000_QL80_.jpg",
  tracks: [
    {name:"Flooded the Face",file:"../audio/lil-uzi-vert/pink-tape/tracks/flooded_the_face.mp3",statId:"#PT_FLOODED"},
    {name:"Suicide Doors",file:"../audio/lil-uzi-vert/pink-tape/tracks/suicide_doors.mp3",statId:"#PT_SUICIDE"},
    {name:"Aye",file:"../audio/lil-uzi-vert/pink-tape/tracks/aye.mp3",statId:"#PT_AYE"},
    {name:"Crush Em",file:"../audio/lil-uzi-vert/pink-tape/tracks/crush_em.mp3",statId:"#PT_CRUSH"},
    {name:"Amped",file:"../audio/lil-uzi-vert/pink-tape/tracks/amped.mp3",statId:"#PT_AMPED"},
    {name:"x2",file:"../audio/lil-uzi-vert/pink-tape/tracks/x2.mp3",statId:"#PT_X2"},
    {name:"Died and Came Back",file:"../audio/lil-uzi-vert/pink-tape/tracks/died_and_came_back.mp3",statId:"#PT_DIED"},
    {name:"Spin Again",file:"../audio/lil-uzi-vert/pink-tape/tracks/spin_again.mp3",statId:"#PT_SPIN"},
    {name:"That Fiya",file:"../audio/lil-uzi-vert/pink-tape/tracks/that_fiya.mp3",statId:"#PT_FIYA"},
    {name:"I Gotta",file:"../audio/lil-uzi-vert/pink-tape/tracks/i_gotta.mp3",statId:"#PT_IGOTTA"},
    {name:"Endless Fashion (feat. Nicki Minaj)",file:"../audio/lil-uzi-vert/pink-tape/tracks/endless_fashion.mp3",statId:"#PT_ENDLESS"},
    {name:"Mama, I'm Sorry",file:"../audio/lil-uzi-vert/pink-tape/tracks/mama_im_sorry.mp3",statId:"#PT_MAMA"},
    {name:"All Alone",file:"../audio/lil-uzi-vert/pink-tape/tracks/all_alone.mp3",statId:"#PT_ALONE"},
    {name:"Nakamura",file:"../audio/lil-uzi-vert/pink-tape/tracks/nakamura.mp3",statId:"#PT_NAKAMURA"},
    {name:"Just Wanna Rock",file:"../audio/lil-uzi-vert/pink-tape/tracks/just_wanna_rock.mp3",statId:"#PT_JWR"},
    {name:"Patience",file:"../audio/lil-uzi-vert/pink-tape/tracks/patience.mp3",statId:"#PT_PATIENCE"},
    {name:"CS",file:"../audio/lil-uzi-vert/pink-tape/tracks/cs.mp3",statId:"#PT_CS"},
    {name:"Werewolf",file:"../audio/lil-uzi-vert/pink-tape/tracks/werewolf.mp3",statId:"#PT_WEREWOLF"},
    {name:"Pluto to Mars",file:"../audio/lil-uzi-vert/pink-tape/tracks/pluto_to_mars.mp3",statId:"#PT_PLUTO"},
    {name:"Days Come and Go",file:"../audio/lil-uzi-vert/pink-tape/tracks/days_come_and_go.mp3",statId:"#PT_DAYS"},
    {name:"Rehab",file:"../audio/lil-uzi-vert/pink-tape/tracks/rehab.mp3",statId:"#PT_REHAB"},
    {name:"The End (feat. BABYMETAL)",file:"../audio/lil-uzi-vert/pink-tape/tracks/the_end.mp3",statId:"#PT_THE_END"}
  ]
},
{
  id: "astroworld",
  title: "AstroWorld.",
  artist: "travis scott",
  year: "2018",
  type: "released",
  tags: ["atroworld","travis scott","astro","world"],
  cover: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4b/Travis_Scott_-_Astroworld.png/250px-Travis_Scott_-_Astroworld.png",
  tracks: []
},
{
  id: "rodeo",
  title: "Rodeo",
  artist: "travis scott",
  year: "2015",
  type: "released",
  tags: ["rodeo","travis scott","2015"],
  cover: "https://upload.wikimedia.org/wikipedia/en/thumb/1/15/Travis_Scott_-_Rodeo.png/250px-Travis_Scott_-_Rodeo.png",
  tracks: []
},
{
  id: "days-before-rodeo",
  title: "Days Before Rodeo",
  artist: "travis scott",
  year: "2014",
  type: "released",
  tags: ["days","rodeo","travis scott","2014"],
  cover: "https://upload.wikimedia.org/wikipedia/en/thumb/5/58/Days_Before_Rodeo_Cover_Art.jpg/250px-Days_Before_Rodeo_Cover_Art.jpg",
  tracks: []
},
{
  id: "bittsmk",
  title: "Birds in the Trap Sing McKnight",
  artist: "travis scott",
  year: "2016",
  type: "released",
  tags: ["birds in the trap","McKnight","travis scott","2016"],
  cover: "https://upload.wikimedia.org/wikipedia/en/thumb/6/61/Travis_Scott_-_Birds_in_the_Trap_Sing_McKnight.png/250px-Travis_Scott_-_Birds_in_the_Trap_Sing_McKnight.png",
  tracks: []
},
{
  id: "jack-boys",
  title: "Jack Boys",
  artist: "travis scott",
  year: "2019",
  type: "released",
  tags: ["Jack boys","travis scott","sofaygo","chase b","2019"],
  cover: "https://upload.wikimedia.org/wikipedia/en/thumb/8/82/JACKBOYS_-_Album_Cover_by_JACKBOYS_%26_Travis_Scott%2C_December_27%2C_2019.jpg/250px-JACKBOYS_-_Album_Cover_by_JACKBOYS_%26_Travis_Scott%2C_December_27%2C_2019.jpg",
  tracks: []
},
{
  id: "jack-boys-2",
  title: "Jack Boys 2",
  artist: "travis scott",
  year: "2025",
  type: "released",
  tags: ["Jack boys","travis scott","sofaygo","chase b","don toliver","2025"],
  cover: "https://upload.wikimedia.org/wikipedia/en/thumb/7/75/JACKBOYS_2_-_Album_Cover_by_JACKBOYS_%26_Travis_Scott.png/250px-JACKBOYS_2_-_Album_Cover_by_JACKBOYS_%26_Travis_Scott.png",
  tracks: []
},
// UNRELEASED
{id:"yandhi",title:"Yandhi",artist:"Kanye West",year:"2018 (unreleased)",type:"unreleased",tags:["kanye","west","yandhi","unreleased","shelved","rap","2018"],cover:"https://upload.wikimedia.org/wikipedia/commons/1/1d/Yandhi_Cover_Art_%28Free_License%29.jpg",tracks:[
    {name:"Chakras",file:"../audio/kanye-west/yandhi/tracks/chakras.mp3",statId:"$YAN_CHAK"},{name:"Garden",file:"../audio/kanye-west/yandhi/tracks/garden.mp3",statId:"$YAN_GARD"},{name:"New Body",file:"../audio/kanye-west/yandhi/tracks/new-body.mp3",statId:"$YAN_NB"},
    {name:"Vibez",file:"../audio/kanye-west/yandhi/tracks/vibez.mp3",statId:"$YAN_VIB"},{name:"Easy",file:"../audio/kanye-west/yandhi/tracks/easy.mp3",statId:"$YAN_EASY"},{name:"Brothers",file:"../audio/kanye-west/yandhi/tracks/brothers.mp3",statId:"$YAN_BRO"},
    {name:"Like God",file:"../audio/kanye-west/yandhi/tracks/like-god.mp3",statId:"$YAN_LG"},{name:"Yandhi",file:"../audio/kanye-west/yandhi/tracks/yandhi-title.mp3",statId:"$YAN_YAN"},{name:"Violent Crimes",file:"../audio/kanye-west/yandhi/tracks/violent-crimes.mp3",statId:"$YAN_VC"},
    {name:"Nah Nah Nah",file:"../audio/kanye-west/yandhi/tracks/nah-nah-nah.mp3",statId:"$YAN_NNN"},{name:"Background Noise",file:"../audio/kanye-west/yandhi/tracks/background-noise.mp3",statId:"$YAN_BN"},
    {name:"True Love",file:"../audio/kanye-west/yandhi/tracks/true-love-yandhi.mp3",statId:"$YAN_TL"},{name:"In the Fire",file:"../audio/kanye-west/yandhi/tracks/in-the-fire.mp3",statId:"$YAN_ITF"}
]},
{id:"turbo-grafx-16",title:"Turbo Grafx 16",artist:"Kanye West",year:"2019 (unreleased)",type:"unreleased",tags:["kanye","west","turbo","grafx","16","unreleased","shelved","rap","2019"],cover:"https://lastfm.freetls.fastly.net/i/u/ar0/68bd0237ddfa94159b35a684e5ee8be7.jpg",tracks:[
    {name:"Nah Nah Nah (OG)",file:"../audio/kanye-west/turbo-grafx-16/tracks/nah-nah-nah-og.mp3",statId:"$TG_NNN"},{name:"Turbo Grafx 16",file:"../audio/kanye-west/turbo-grafx-16/tracks/turbo-title.mp3",statId:"$TG_TG"},
    {name:"Water (Coachella)",file:"../audio/kanye-west/turbo-grafx-16/tracks/water-coachella.mp3",statId:"$TG_WAT"},{name:"Closed on Sunday (Early)",file:"../audio/kanye-west/turbo-grafx-16/tracks/closed-early.mp3",statId:"$TG_COS"},
    {name:"Follow God (Rough)",file:"../audio/kanye-west/turbo-grafx-16/tracks/follow-god-rough.mp3",statId:"$TG_FG"},{name:"God's Country",file:"../audio/kanye-west/turbo-grafx-16/tracks/gods-country.mp3",statId:"$TG_GC"},
    {name:"Everything We Need (Demo)",file:"../audio/kanye-west/turbo-grafx-16/tracks/ewen-demo.mp3",statId:"$TG_EWN"},{name:"Hands On (Early)",file:"../audio/kanye-west/turbo-grafx-16/tracks/hands-on-early.mp3",statId:"$TG_HO"},
    {name:"Use This Gospel (Demo)",file:"../audio/kanye-west/turbo-grafx-16/tracks/utg-demo.mp3",statId:"$TG_UTG"},{name:"Jesus Is Lord (Rough)",file:"../audio/kanye-west/turbo-grafx-16/tracks/jil-rough.mp3",statId:"$TG_JIL"}
]},
{id:"maybe-maybe",title:"maybe (Maybe).",artist:"Rhap5ody",year:"2029 (soon)",type:"unreleased",tags:["rhap5dy","maybe","2029"],cover:"https://raw.githubusercontent.com/bguhm/bguhm.github.io/main/music/albums/maybe-maybe/maybe-maybe-cover-art.png",tracks:[
    {name:"slackrr.",file:"../audio/rhap5ody/maybe-maybe/tracks/slackrr.mp3",statId:"$MM_SLK"},{name:"Caramel eyes.",file:"../audio/rhap5ody/maybe-maybe/tracks/caramel-eyes.mp3",statId:"$MM_CE"},
    {name:"PUNK HAZARD.",file:"../audio/rhap5ody/maybe-maybe/tracks/punk-hazard.mp3",statId:"$MM_PH"},{name:"HOUND.",file:"../audio/rhap5ody/maybe-maybe/tracks/hound.mp3",statId:"$MM_HND"},
    {name:"Arizona Girl",file:"../audio/rhap5ody/maybe-maybe/tracks/arizona-girl.mp3",statId:"$MM_AZ"},{name:"MARIGOLD.",file:"../audio/rhap5ody/maybe-maybe/tracks/marigold.mp3",statId:"$MM_MG"},
    {name:"Besto Friendo",file:"../audio/rhap5ody/maybe-maybe/tracks/besto-friendo.mp3",statId:"$MM_BF"},{name:"HippoCript.",file:"../audio/rhap5ody/maybe-maybe/tracks/hippocript.mp3",statId:"$MM_HC"},
    {name:"AloneAgain",file:"../audio/rhap5ody/maybe-maybe/tracks/alone-again.mp3",statId:"$MM_AA"},{name:"RoofTop",file:"../audio/rhap5ody/maybe-maybe/tracks/rooftop.mp3",statId:"$MM_RT"},
    {name:"November.",file:"../audio/rhap5ody/maybe-maybe/tracks/november.mp3",statId:"$MM_NOV"},{name:"Street",file:"../audio/rhap5ody/maybe-maybe/tracks/street.mp3",statId:"$MM_STR"},
    {name:"Self Conscious.",file:"../audio/rhap5ody/maybe-maybe/tracks/self-conscious.mp3",statId:"$MM_SC"},{name:"Scribble.",file:"../audio/rhap5ody/maybe-maybe/tracks/scribble.mp3",statId:"$MM_SCR"},
    {name:"Feelings In A Bottle.",file:"../audio/rhap5ody/maybe-maybe/tracks/feelings-in-a-bottle.mp3",statId:"$MM_FIAB"},{name:"SoloCup.",file:"../audio/rhap5ody/maybe-maybe/tracks/solocup.mp3",statId:"$MM_SOL"},
    {name:"Bg.uhm",file:"../audio/rhap5ody/maybe-maybe/tracks/bg-uhm.mp3",statId:"$MM_BG"},{name:"6:27",file:"../audio/rhap5ody/maybe-maybe/tracks/6-27.mp3",statId:"$MM_627"},
    {name:"Daisy.",file:"../audio/rhap5ody/maybe-maybe/tracks/daisy.mp3",statId:"$MM_DAISY"},{name:"Maybe (Maybe).",file:"../audio/rhap5ody/maybe-maybe/tracks/maybe-maybe.m4a",statId:"$MM_MM"}
]},
{id:"syndicate",title:"Syndicate",artist:"Rhap5ody",year:"2029 (soon)",type:"unreleased",tags:["syndicate","rhap5ody","2029"],cover:"https://raw.githubusercontent.com/bguhm/bguhm.github.io/main/music/albums/syndicate/Untitled157_20260219144858.png",tracks:[
    {name:"BOHEMETH.",file:"../audio/rhap5ody/syndicate/tracks/bohemeth.mp3",statId:"$SYN_BOH"}
]},
{id:"nuralistics",title:"NURALISTICS",artist:"Rhap5ody",year:"2029 (soon)",type:"unreleased",tags:["NURALISTICS","rhap5ody","insomnia","2029"],cover:"https://raw.githubusercontent.com/bguhm/bguhm.github.io/main/music/albums/NURALISTICS/IMG_6099.png",tracks:[
    {name:"1",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"2",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"3",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"4",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"5",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"6",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"7",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"8",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"9",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"10",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"11",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"12",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"13.",file:"../audio/rhap5ody/nuralistics/tracks/insomnia.mp3",statId:"$NUR_INS"}
]},
{id:"r5",title:"rhapsody",artist:"Rhap5ody",year:"2029 (soon)",type:"unreleased",tags:["rhap5ody","r5","2029"],cover:"https://raw.githubusercontent.com/bguhm/bguhm.github.io/main/music/albums/r5/IMG_6100.png",tracks:[
    {name:"R5 DO THAT SHIT.",file:"../audio/rhap5ody/r5/tracks/r5dothatshit.mp3",statId:"$R5_R5DOTHATSHIT"},
    {name:"Tital",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"psych.",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"too high",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"IQ",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"MyWorld.",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"}
]},
{id:"eternal-atake-og",title:"Eternal Atake",artist:"Lil Uzi Vert",year:"leaked 2019",type:"unreleased",tags:["liluzivert","ea","2019"],cover:"https://i.redd.it/uby2xk33ybd11.jpg",tracks:[
    {name:"Lets Go",file:"../audio/lil-uzi-vert/eternal-atake-og/tracks/letsgo.m4a",statId:"$EA_LETSGO"},
    {name:"Bands",file:"../audio/lil-uzi-vert/eternal-atake-og/tracks/bands.m4a",statId:"$EA_BANDS"},
    {name:"You A 10",file:"../audio/lil-uzi-vert/eternal-atake-og/tracks/youa10.m4a",statId:"$EA_YOUA10"},
    {name:"Put That Money Up",file:"../audio/lil-uzi-vert/eternal-atake-og/tracks/putthatmoneyup.m4a",statId:"$EA_PUTTHATMONEYUP"},
    {name:"Blue Tips",file:"../audio/lil-uzi-vert/eternal-atake-og/tracks/bluetips.m4a",statId:"$EA_BLUETIPS"},
    {name:"Sticky",file:"../audio/lil-uzi-vert/eternal-atake-og/tracks/sticky.m4a",statId:"$EA_STICKY"},
    {name:"Take My Cake",file:"../audio/lil-uzi-vert/eternal-atake-og/tracks/takemycake.m4a",statId:"$EA_TAKEMYCAKE"},
    {name:"All My Guap",file:"../audio/lil-uzi-vert/eternal-atake-og/tracks/allmyguap.m4a",statId:"$EA_ALLMYGUAP"},
    {name:"Keep It Real",file:"../audio/lil-uzi-vert/eternal-atake-og/tracks/keepitreal.m4a",statId:"$EA_KEEPITREAL"},
    {name:"Diamonds",file:"../audio/lil-uzi-vert/eternal-atake-og/tracks/diamonds.m4a",statId:"$EA_DIAMONDS"},
    {name:"Of Course",file:"../audio/lil-uzi-vert/eternal-atake-og/tracks/ofcourse.m4a",statId:"$EA_OFCOURSE"},
    {name:"1600 (RAGER ANTHEM)",file:"../audio/lil-uzi-vert/eternal-atake-og/tracks/1600rageranthem.m4a",statId:"$EA_1600RAGERANTHEM"},
    {name:"Not The Same",file:"../audio/lil-uzi-vert/eternal-atake-og/tracks/notthesame.m4a",statId:"$EA_NOTTHESAME"},
    {name:"Closure",file:"../audio/lil-uzi-vert/eternal-atake-og/tracks/closure.m4a",statId:"$EA_CLOSURE"},
    {name:"Extraed Out",file:"../audio/lil-uzi-vert/eternal-atake-og/tracks/extraedout.m4a",statId:"$EA_EXTRAEDOUT"},
    {name:"Run It Up",file:"../audio/lil-uzi-vert/eternal-atake-og/tracks/runitup.m4a",statId:"$EA_RUNITUP"},
    {name:"Extra - New Patek",file:"../audio/lil-uzi-vert/eternal-atake-og/tracks/extranewpatek.m4a",statId:"$EA_EXTRANEWPATEK"},
    {name:"Extra - The End Is Near",file:"../audio/lil-uzi-vert/eternal-atake-og/tracks/extratheendisnear.m4a",statId:"$EA_EXTRATHEENDISNEAR"}
]},
{id:"16-29-collab",title:"16*29",artist:"Lil Uzi Vert & Playboi Carti",year:"unreleased",type:"unreleased",tags:["liluzivert","playboicarti","collab","1629"],cover:"https://i.pinimg.com/736x/59/4c/1c/594c1c54684244b2feda1fc9650e4f14.jpg",tracks:[
    {name:"Intro (16*29)",file:"../audio/lil-uzi-vert/16-29-collab/tracks/intro1629.mp3",statId:"$1629_INTRO"},
    {name:"Fell In Luv",file:"../audio/lil-uzi-vert/16-29-collab/tracks/fellinluv.mp3",statId:"$1629_FELLINLUV"},
    {name:"No Stylist",file:"../audio/lil-uzi-vert/16-29-collab/tracks/nostylist.mp3",statId:"$1629_NOSTYLIST"},
    {name:"Drip Season",file:"../audio/lil-uzi-vert/16-29-collab/tracks/dripseason.mp3",statId:"$1629_DRIPSEASON"},
    {name:"Twin Turbos",file:"../audio/lil-uzi-vert/16-29-collab/tracks/twinturbos.mp3",statId:"$1629_TWINTURBOS"},
    {name:"Slatt Walk",file:"../audio/lil-uzi-vert/16-29-collab/tracks/slattwalk.mp3",statId:"$1629_SLATTWALK"},
    {name:"On Site (feat. Lil Uzi Vert)",file:"../audio/lil-uzi-vert/16-29-collab/tracks/onsite.mp3",statId:"$1629_ONSITE"},
    {name:"Rockstar Shit",file:"../audio/lil-uzi-vert/16-29-collab/tracks/rockstarshit.mp3",statId:"$1629_ROCKSTARSHIT"},
    {name:"Purple Haze",file:"../audio/lil-uzi-vert/16-29-collab/tracks/purplehaze.mp3",statId:"$1629_PURPLEHAZE"},
    {name:"Rager 4 Life",file:"../audio/lil-uzi-vert/16-29-collab/tracks/rager4life.mp3",statId:"$1629_RAGER4LIFE"},
    {name:"No Ceilings",file:"../audio/lil-uzi-vert/16-29-collab/tracks/noceilings.mp3",statId:"$1629_NOCEILINGS"},
    {name:"Eternal Rage",file:"../audio/lil-uzi-vert/16-29-collab/tracks/eternalrage.mp3",statId:"$1629_ETERNALRAGE"},
    {name:"Iced Out Halo",file:"../audio/lil-uzi-vert/16-29-collab/tracks/icedouthalo.mp3",statId:"$1629_ICEDOUTHALO"},
    {name:"Carti Season",file:"../audio/lil-uzi-vert/16-29-collab/tracks/cartiseason.mp3",statId:"$1629_CARTISEASON"},
    {name:"Outro (End Of Days)",file:"../audio/lil-uzi-vert/16-29-collab/tracks/outroendofdays.mp3",statId:"$1629_OUTRO"}
]},
{
  id: "bastard",
  title: "Bastard",
  artist: "Tyler, the Creator",
  year: "2009",
  type: "unreleased",
  tags: ["tyler the creator","rap","2009","mixtape"],
  cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/bastard/covers/IMG_6376.png",
  tracks: [
    {name:"Bastard",file:"../audio/tyler-the-creator/bastard/tracks/bastard.mp3",statId:"$BAS_BAS"},
    {name:"Seven",file:"../audio/tyler-the-creator/bastard/tracks/seven.mp3",statId:"$BAS_SEV"},
    {name:"Odd Toddlers (feat. Casey Veggies)",file:"../audio/tyler-the-creator/bastard/tracks/odd-toddlers.mp3",statId:"$BAS_OT"},
    {name:"French!",file:"../audio/tyler-the-creator/bastard/tracks/french.mp3",statId:"$BAS_FR"},
    {name:"Blow",file:"../audio/tyler-the-creator/bastard/tracks/blow.mp3",statId:"$BAS_BL"},
    {name:"Pigs Fly (feat. Domo Genesis)",file:"../audio/tyler-the-creator/bastard/tracks/pigs-fly.mp3",statId:"$BAS_PF"},
    {name:"Parade",file:"../audio/tyler-the-creator/bastard/tracks/parade.mp3",statId:"$BAS_PAR"},
    {name:"Slow It Down (feat. Hodgy)",file:"../audio/tyler-the-creator/bastard/tracks/slow-it-down.mp3",statId:"$BAS_SID"},
    {name:"AssMilk (feat. Earl Sweatshirt)",file:"../audio/tyler-the-creator/bastard/tracks/assmilk.mp3",statId:"$BAS_AM"},
    {name:"VCR/Wheels",file:"../audio/tyler-the-creator/bastard/tracks/vcr-wheels.mp3",statId:"$BAS_VW"},
    {name:"Session (feat. Hodgy & Mike G)",file:"../audio/tyler-the-creator/bastard/tracks/session.mp3",statId:"$BAS_SES"},
    {name:"Sarah",file:"../audio/tyler-the-creator/bastard/tracks/sarah.mp3",statId:"$BAS_SAR"},
    {name:"Jack and the Beanstalk",file:"../audio/tyler-the-creator/bastard/tracks/jack-and-the-beanstalk.mp3",statId:"$BAS_JB"},
    {name:"Tina (feat. Jasper & Taco)",file:"../audio/tyler-the-creator/bastard/tracks/tina.mp3",statId:"$BAS_TIN"},
    {name:"Inglorious",file:"../audio/tyler-the-creator/bastard/tracks/inglorious.mp3",statId:"$BAS_ING"}
  ]
},
{
id: "no-luv-lost",
title: "No Luv Lost",
artist: "lil-uzi-vert",
year: "leaked?",
type: "unreleased",
tags: [],
cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/no-luv-lost/covers/IMG_6389.jpeg",
tracks: [
    {name:"title",file:"../audio/lil-uzi-vert/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"title",file:"../audio/lil-uzi-vert/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"title",file:"../audio/lil-uzi-vert/album/tracks/name.mp3",statId:"$ID_NME"}
]
},
{
id: "wlr-v1",
title: "whole lotta red v1",
artist: "playboi-carti",
year: "leaked?",
type: "unreleased",
tags: [],
cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/whole-lotta-red-v1/covers/IMG_6392.jpeg",
tracks: [
    {name:"Not Real",file:"../audio/playboi-carti/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"Proud of You",file:"../audio/playboi-carti/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"Neon",file:"../audio/playboi-carti/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"Nine Nine",file:"../audio/playboi-carti/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"Vivienne Westwood",file:"../audio/playboi-carti/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"Designer Shoes",file:"../audio/playboi-carti/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"Bouldercrest (ft. Offset)",file:"../audio/playboi-carti/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"Moshpit (ft. NGeeYL)",file:"../audio/playboi-carti/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"Fashion Killa",file:"../audio/playboi-carti/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"Shopping Spree",file:"../audio/playboi-carti/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"I Promise You !",file:"../audio/playboi-carti/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"Back Up (ft. Offset)",file:"../audio/playboi-carti/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"Pop Bottles",file:"../audio/playboi-carti/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"Fuck it Up",file:"../audio/playboi-carti/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"Buffy the Body",file:"../audio/playboi-carti/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"RiRi",file:"../audio/playboi-carti/album/tracks/name.mp3",statId:"$ID_NME"}
]
},
{
id: "the-world-pt1",
title: "TheWorld pt.1",
artist: "Rhap5ody",
year: "2029",
type: "unreleased",
tags: [],
cover: "https://raw.githubusercontent.com/soundscapeonline/soundscapeonline.github.io/main/audio/theworldpt1/covers/IMG_6393.jpeg",
tracks: [
    {name:"90 degrees in the summer",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"Untitled",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"Untitled",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"Untitled",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"Friday",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"Life",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"influence",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"},
    {name:"reverse",file:"../audio/rhap5ody/album/tracks/name.mp3",statId:"$ID_NME"}
]
},
{
  id: "phosephenes",
  title: "Phosphenes.",
  artist: "Rhap5ody",
  year: "2029",
  type: "unreleased",
  tags: ["Phonesphenes","phonesphenes","helloworld","HelloWorld","BeauTeen","beauteen","Moron Child","moron child"],
  cover: "https://raw.githubusercontent.com/dontevenjokelad/dontevenjokelad.github.io/main/audio/phosphenes/covers/Phosphenes.png",
  tracks: [
    {name:"HelloWorld!",file:"../audio/rhap5ody/phosphenes/tracks/hello-world.mp3",statId:"$PS_HW"},
    {name:"Colorful World.",file:"../audio/rhap5ody/phosphenes/tracks/colorful-world.mp3",statId:"$PS_CW"},
    {name:"Blood Flowers",file:"../audio/rhap5ody/phosphenes/tracks/blood-flowers.mp3",statId:"$PS_BF"},
    {name:"Bloom.",file:"../audio/rhap5ody/phosphenes/tracks/bloom.mp3",statId:"$PS_BM"},
    {name:"Slackerish.",file:"../audio/rhap5ody/phosphenes/tracks/slackerish.mp3",statId:"$PS_ISH"},
    {name:"YartK",file:"../audio/rhap5ody/phosphenes/tracks/yartk.mp3",statId:"$PS_YK"},
    {name:"Moron Child.",file:"../audio/rhap5ody/phosphenes/tracks/moron-child.mp3",statId:"$PS_MC"},
    {name:"PerfectWorld.",file:"../audio/rhap5ody/phosphenes/tracks/perfect-world.mp3",statId:"$PS_PW"}
  ]
},
{
  id: "theworldpt2",
  title: "TheWorld pt.2",
  artist: "Rhap5ody",
  year: "2029",
  type: "unreleased",
  tags: [],
  cover: "",
  tracks: [
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"}
]
},
{
  id: "theworldpt3",
  title: "TheWorld pt.3",
  artist: "Rhap5ody",
  year: "2029",
  type: "unreleased",
  tags: [],
  cover: "",
  tracks: [
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"}
]
},
{
  id: "theworldpt4",
  title: "TheWorld pt.4",
  artist: "Rhap5ody",
  year: "2029",
  type: "unreleased",
  tags: [],
  cover: "",
  tracks: [
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"}
]
},
{
  id: "slackrr",
  title: "slackrr",
  artist: "Rhap5ody",
  year: "2029",
  type: "unreleased",
  tags: ["rhapsody","2029"],
  cover: "",
  tracks: [
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"}
]
}, 
{
  id: "jayda",
  title: "Jayda.",
  artist: "Rhap5ody",
  year: "2029",
  type: "unreleased",
  tags: [],
  cover: "",
  tracks: [
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"},
    {name:"title",file:"../audio/artist/album/tracks/name.type",statId:"$HI_BY"}
]
},
];